<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>SufiChain.SufiPlatform.HelpDesk.KnowledgeBase</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../../pro-modules/helpdesk/src/SufiChain.SufiPlatform.HelpDesk.KnowledgeBase.Application/SufiChain.SufiPlatform.HelpDesk.KnowledgeBase.Application.csproj" />
    <ProjectReference Include="../SufiChain.SufiPlatform.HelpDesk.KnowledgeBase.TestBase/SufiChain.SufiPlatform.HelpDesk.KnowledgeBase.TestBase.csproj" />
    <PackageReference Include="Volo.Abp.TestBase" Version="$(AbpVersion)" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="Shouldly" Version="4.3.0" />
    <PackageReference Include="NSubstitute" Version="5.3.0" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" PrivateAssets="All" />
  </ItemGroup>
</Project>
