<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup><LangVersion>latest</LangVersion>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>MyCompanyName.MyProjectName</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

	  <!-- <TEMPLATE-REMOVE> -->
	  <ItemGroup>
	    <PackageReference Include="OpenIddict.Abstractions" Version="$(OpenIddictVersion)" />
	    <ProjectReference Include="..\..\..\..\..\src\framework\SufiChain.SufiPlatform.Core\SufiChain.SufiPlatform.Core.csproj" />
	    <ProjectReference Include="..\..\..\..\..\src\framework\SufiChain.SufiPlatform.Data\SufiChain.SufiPlatform.Data.csproj" />
	    <ProjectReference Include="..\MyCompanyName.MyProjectName.Domain.Shared\MyCompanyName.MyProjectName.Domain.Shared.csproj" />
	  </ItemGroup>
	  <!-- </TEMPLATE-REMOVE> -->

	  <!-- <TEMPLATE-REMOVE> -->
  <ItemGroup>
    <ProjectReference Include="..\..\..\..\..\modules\permissions\src\SufiChain.SufiPlatform.Permissions.Domain\SufiChain.SufiPlatform.Permissions.Domain.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\settings\src\SufiChain.SufiPlatform.Settings.Domain\SufiChain.SufiPlatform.Settings.Domain.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\features\src\SufiChain.SufiPlatform.Features.Domain\SufiChain.SufiPlatform.Features.Domain.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\audit-logging\src\SufiChain.SufiPlatform.AuditLogging.Domain\SufiChain.SufiPlatform.AuditLogging.Domain.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\jobs\src\SufiChain.SufiPlatform.BackgroundJobs.Domain\SufiChain.SufiPlatform.BackgroundJobs.Domain.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\identity\src\SufiChain.SufiPlatform.Identity.Domain\SufiChain.SufiPlatform.Identity.Domain.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\identity\src\SufiChain.SufiPlatform.Permissions.Domain.Identity\SufiChain.SufiPlatform.Permissions.Domain.Identity.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\users\src\SufiChain.SufiPlatform.Users.Domain\SufiChain.SufiPlatform.Users.Domain.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\tenants\src\SufiChain.SufiPlatform.Tenants.Domain\SufiChain.SufiPlatform.Tenants.Domain.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\openiddict\src\SufiChain.SufiPlatform.OpenIddict.Domain\SufiChain.SufiPlatform.OpenIddict.Domain.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\openiddict\src\SufiChain.SufiPlatform.Permissions.Domain.OpenIddict\SufiChain.SufiPlatform.Permissions.Domain.OpenIddict.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\calendar\src\SufiChain.SufiPlatform.Calendar.Domain\SufiChain.SufiPlatform.Calendar.Domain.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\short-links\src\SufiChain.SufiPlatform.ShortLinks.Domain\SufiChain.SufiPlatform.ShortLinks.Domain.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\tags\src\SufiChain.SufiPlatform.Tags.Domain\SufiChain.SufiPlatform.Tags.Domain.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\menus\src\SufiChain.SufiPlatform.Menus.Domain\SufiChain.SufiPlatform.Menus.Domain.csproj" />
  </ItemGroup>
	  <!-- </TEMPLATE-REMOVE> -->

<!-- <TEMPLATE-ONLY>
	  <ItemGroup>
	    <PackageReference Include="OpenIddict.Abstractions" Version="$(OpenIddictVersion)" />
	    <PackageReference Include="SufiChain.SufiPlatform.Core" Version="$(SufiVersion)" />
	    <PackageReference Include="SufiChain.SufiPlatform.Data" Version="$(SufiVersion)" />
	    <ProjectReference Include="..\MyCompanyName.MyProjectName.Domain.Shared\MyCompanyName.MyProjectName.Domain.Shared.csproj" />
	    <PackageReference Include="SufiChain.SufiPlatform.Calendar.Domain" Version="$(SufiVersion)" />
	    <PackageReference Include="SufiChain.SufiPlatform.Localization.Domain" Version="$(SufiVersion)" />
	    <PackageReference Include="SufiChain.SufiPlatform.SufiAI.Domain" Version="$(SufiVersion)" />
	    <PackageReference Include="SufiChain.SufiPlatform.FileManager.Domain" Version="$(SufiVersion)" />
     <PackageReference Include="SufiChain.SufiPlatform.Permissions.Domain" Version="$(SufiVersion)" />
     <PackageReference Include="SufiChain.SufiPlatform.Settings.Domain" Version="$(SufiVersion)" />
     <PackageReference Include="SufiChain.SufiPlatform.Features.Domain" Version="$(SufiVersion)" />
     <PackageReference Include="SufiChain.SufiPlatform.AuditLogging.Domain" Version="$(SufiVersion)" />
     <PackageReference Include="SufiChain.SufiPlatform.BackgroundJobs.Domain" Version="$(SufiVersion)" />
     <PackageReference Include="SufiChain.SufiPlatform.Identity.Domain" Version="$(SufiVersion)" />
     <PackageReference Include="SufiChain.SufiPlatform.Permissions.Domain.Identity" Version="$(SufiVersion)" />
     <PackageReference Include="SufiChain.SufiPlatform.Users.Domain" Version="$(SufiVersion)" />
     <PackageReference Include="SufiChain.SufiPlatform.Tenants.Domain" Version="$(SufiVersion)" />
     <PackageReference Include="SufiChain.SufiPlatform.OpenIddict.Domain" Version="$(SufiVersion)" />
     <PackageReference Include="SufiChain.SufiPlatform.Permissions.Domain.OpenIddict" Version="$(SufiVersion)" />
     <PackageReference Include="SufiChain.SufiPlatform.ShortLinks.Domain" Version="$(SufiVersion)" />
     <PackageReference Include="SufiChain.SufiPlatform.Tags.Domain" Version="$(SufiVersion)" />
     <PackageReference Include="SufiChain.SufiPlatform.Menus.Domain" Version="$(SufiVersion)" />
	  </ItemGroup>
	  </TEMPLATE-ONLY> -->

</Project>
