<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup><LangVersion>latest</LangVersion>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>MyCompanyName.MyProjectName</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

	  <!-- <TEMPLATE-REMOVE> -->
	  <ItemGroup>
	    <PackageReference Include="OpenIddict.Abstractions" Version="$(OpenIddictVersion)" />
	    <ProjectReference Include="..\..\..\..\..\src\framework\SufiChain.SufiAbp.Core\SufiChain.SufiAbp.Core.csproj" />
	    <ProjectReference Include="..\..\..\..\..\src\framework\SufiChain.SufiAbp.Data\SufiChain.SufiAbp.Data.csproj" />
	    <ProjectReference Include="..\..\..\..\..\src\framework\SufiChain.SufiAbp.Messaging\SufiChain.SufiAbp.Messaging.csproj" />
	    <ProjectReference Include="..\MyCompanyName.MyProjectName.Domain.Shared\MyCompanyName.MyProjectName.Domain.Shared.csproj" />
	  </ItemGroup>
	  <!-- </TEMPLATE-REMOVE> -->

	  <!-- <TEMPLATE-REMOVE> -->
  <ItemGroup>
    <ProjectReference Include="..\..\..\..\..\modules\permission-management\src\SufiChain.SufiAbp.PermissionManagement.Domain\SufiChain.SufiAbp.PermissionManagement.Domain.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\setting-management\src\SufiChain.SufiAbp.SettingManagement.Domain\SufiChain.SufiAbp.SettingManagement.Domain.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\feature-management\src\SufiChain.SufiAbp.FeatureManagement.Domain\SufiChain.SufiAbp.FeatureManagement.Domain.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\audit-logging\src\SufiChain.SufiAbp.AuditLogging.Domain\SufiChain.SufiAbp.AuditLogging.Domain.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\background-jobs\src\SufiChain.SufiAbp.BackgroundJobs.Domain\SufiChain.SufiAbp.BackgroundJobs.Domain.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\identity\src\SufiChain.SufiAbp.Identity.Domain\SufiChain.SufiAbp.Identity.Domain.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\identity\src\SufiChain.SufiAbp.PermissionManagement.Domain.Identity\SufiChain.SufiAbp.PermissionManagement.Domain.Identity.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\users\src\SufiChain.SufiAbp.Users.Domain\SufiChain.SufiAbp.Users.Domain.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\tenant-management\src\SufiChain.SufiAbp.TenantManagement.Domain\SufiChain.SufiAbp.TenantManagement.Domain.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\openiddict\src\SufiChain.SufiAbp.OpenIddict.Domain\SufiChain.SufiAbp.OpenIddict.Domain.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\openiddict\src\SufiChain.SufiAbp.PermissionManagement.Domain.OpenIddict\SufiChain.SufiAbp.PermissionManagement.Domain.OpenIddict.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\calendar\src\SufiChain.SufiAbp.Calendar.Domain\SufiChain.SufiAbp.Calendar.Domain.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\short-link-generator\src\SufiChain.SufiAbp.ShortLinkGenerator.Domain\SufiChain.SufiAbp.ShortLinkGenerator.Domain.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\tags-management\src\SufiChain.SufiAbp.TagsManagement.Domain\SufiChain.SufiAbp.TagsManagement.Domain.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\menu-management\src\SufiChain.SufiAbp.MenuManagement.Domain\SufiChain.SufiAbp.MenuManagement.Domain.csproj" />
  </ItemGroup>
	  <!-- </TEMPLATE-REMOVE> -->

<!-- <TEMPLATE-ONLY>
	  <ItemGroup>
	    <PackageReference Include="OpenIddict.Abstractions" Version="$(OpenIddictVersion)" />
	    <PackageReference Include="SufiChain.SufiAbp.Core" Version="$(SufiVersion)" />
	    <PackageReference Include="SufiChain.SufiAbp.Data" Version="$(SufiVersion)" />
	    <ProjectReference Include="..\MyCompanyName.MyProjectName.Domain.Shared\MyCompanyName.MyProjectName.Domain.Shared.csproj" />
	    <PackageReference Include="SufiChain.SufiAbp.Messaging" Version="$(SufiVersion)" />
	    <PackageReference Include="SufiChain.SufiAbp.Calendar.Domain" Version="$(SufiVersion)" />
	    <PackageReference Include="SufiChain.SufiAbp.LocalizationManagement.Domain" Version="$(SufiVersion)" />
	    <PackageReference Include="SufiChain.SufiAbp.AI.Domain" Version="$(SufiVersion)" />
	    <PackageReference Include="SufiChain.SufiAbp.FileManager.Domain" Version="$(SufiVersion)" />
     <PackageReference Include="SufiChain.SufiAbp.PermissionManagement.Domain" Version="$(SufiVersion)" />
     <PackageReference Include="SufiChain.SufiAbp.SettingManagement.Domain" Version="$(SufiVersion)" />
     <PackageReference Include="SufiChain.SufiAbp.FeatureManagement.Domain" Version="$(SufiVersion)" />
     <PackageReference Include="SufiChain.SufiAbp.AuditLogging.Domain" Version="$(SufiVersion)" />
     <PackageReference Include="SufiChain.SufiAbp.BackgroundJobs.Domain" Version="$(SufiVersion)" />
     <PackageReference Include="SufiChain.SufiAbp.Identity.Domain" Version="$(SufiVersion)" />
     <PackageReference Include="SufiChain.SufiAbp.PermissionManagement.Domain.Identity" Version="$(SufiVersion)" />
     <PackageReference Include="SufiChain.SufiAbp.Users.Domain" Version="$(SufiVersion)" />
     <PackageReference Include="SufiChain.SufiAbp.TenantManagement.Domain" Version="$(SufiVersion)" />
     <PackageReference Include="SufiChain.SufiAbp.OpenIddict.Domain" Version="$(SufiVersion)" />
     <PackageReference Include="SufiChain.SufiAbp.PermissionManagement.Domain.OpenIddict" Version="$(SufiVersion)" />
     <PackageReference Include="SufiChain.SufiAbp.ShortLinkGenerator.Domain" Version="$(SufiVersion)" />
     <PackageReference Include="SufiChain.SufiAbp.TagsManagement.Domain" Version="$(SufiVersion)" />
     <PackageReference Include="SufiChain.SufiAbp.MenuManagement.Domain" Version="$(SufiVersion)" />
	  </ItemGroup>
	  </TEMPLATE-ONLY> -->

</Project>
