<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
        <TargetFrameworks>netstandard2.1;net10.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <RootNamespace>SufiChain.SufiAbp.Calendar</RootNamespace>
    <GenerateEmbeddedFilesManifest>true</GenerateEmbeddedFilesManifest>
    <IsPackable>true</IsPackable>
  </PropertyGroup>
  <PropertyGroup>
    <PackageId>SufiChain.SufiAbp.Calendar.Domain.Shared</PackageId>
    <Description>Calendar module domain shared layer for Sufi Platform.</Description>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Volo.Abp.Ddd.Domain.Shared" Version="$(AbpVersion)" />
    <ProjectReference Include="../../../../framework/SufiChain.SufiAbp.Validation/SufiChain.SufiAbp.Validation.csproj" />
    <ProjectReference Include="../../../../framework/SufiChain.SufiAbp.Features/SufiChain.SufiAbp.Features.csproj" />
    <ProjectReference Include="../../../../framework/SufiChain.SufiAbp.UI.Domain.Shared/SufiChain.SufiAbp.UI.Domain.Shared.csproj" />
    <ProjectReference Include="..\..\..\..\framework\SufiChain.SufiAbp.UI.Abstractions\SufiChain.SufiAbp.UI.Abstractions.csproj" />
    <PackageReference Include="Microsoft.Extensions.FileProviders.Embedded" Version="$(MicrosoftExtensionsFileProvidersEmbeddedVersion)" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Localization\Calendar\*.json" />
    <Content Remove="Localization\Calendar\*.json" />
  </ItemGroup>
</Project>
