<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>SufiChain.SufiAbp.AI</RootNamespace>
    <PackageId>SufiChain.SufiAbp.AI.Application</PackageId>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\framework\SufiChain.SufiAbp.Ddd.Application\SufiChain.SufiAbp.Ddd.Application.csproj" />
    <PackageReference Include="Volo.Abp.Mapperly" Version="$(AbpVersion)" />
    <ProjectReference Include="..\..\..\file-manager\src\SufiChain.SufiAbp.FileManager.Application\SufiChain.SufiAbp.FileManager.Application.csproj" />
    <ProjectReference Include="..\..\..\localization-management\src\SufiChain.SufiAbp.LocalizationManagement.Application.Contracts\SufiChain.SufiAbp.LocalizationManagement.Application.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SufiChain.SufiAbp.AI.Application.Contracts\SufiChain.SufiAbp.AI.Application.Contracts.csproj" />
    <ProjectReference Include="..\SufiChain.SufiAbp.AI.Domain\SufiChain.SufiAbp.AI.Domain.csproj" />
  </ItemGroup>

</Project>
