<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>SufiChain.Chat</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MailKit" Version="$(MailKitVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\framework\SufiChain.SufiAbp.AspNetCore.Mvc\SufiChain.SufiAbp.AspNetCore.Mvc.csproj" />
    <ProjectReference Include="..\..\..\..\framework\SufiChain.SufiAbp.BackgroundWorkers\SufiChain.SufiAbp.BackgroundWorkers.csproj" />
    <ProjectReference Include="..\..\..\..\framework\SufiChain.SufiAbp.Ddd.Application\SufiChain.SufiAbp.Ddd.Application.csproj" />
    <ProjectReference Include="..\..\..\..\framework\SufiChain.SufiAbp.Features\SufiChain.SufiAbp.Features.csproj" />
    <ProjectReference Include="..\..\..\..\framework\SufiChain.SufiAbp.Messaging\SufiChain.SufiAbp.Messaging.csproj" />
    <ProjectReference Include="..\..\..\..\framework\SufiChain.SufiAbp.TextTemplating.Scriban\SufiChain.SufiAbp.TextTemplating.Scriban.csproj" />
    <ProjectReference Include="..\..\..\..\framework\SufiChain.SufiAbp.TextTemplating\SufiChain.SufiAbp.TextTemplating.csproj" />
    <ProjectReference Include="..\..\..\setting-management\src\SufiChain.SufiAbp.SettingManagement.Domain\SufiChain.SufiAbp.SettingManagement.Domain.csproj" />
    <ProjectReference Include="..\..\..\tenant-management\src\SufiChain.SufiAbp.TenantManagement.Domain\SufiChain.SufiAbp.TenantManagement.Domain.csproj" />
    <ProjectReference Include="..\SufiChain.Chat.Application.Contracts\SufiChain.Chat.Application.Contracts.csproj" />
    <ProjectReference Include="..\SufiChain.Chat.Application\SufiChain.Chat.Application.csproj" />
    <ProjectReference Include="..\SufiChain.Chat.Connector\SufiChain.Chat.Connector.csproj" />
    <ProjectReference Include="..\SufiChain.Chat.Domain\SufiChain.Chat.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Templates\*.tpl" />
    <Content Remove="Templates\*.tpl" />
  </ItemGroup>
</Project>
