<Project Sdk="Microsoft.NET.Sdk">


  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>SufiChain.SufiAbp.Users.EntityFrameworkCore</AssemblyName>
    <PackageId>SufiChain.SufiAbp.Users.EntityFrameworkCore</PackageId>
    <RootNamespace>SufiChain.SufiAbp.Users</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SufiChain.SufiAbp.Users.Domain\SufiChain.SufiAbp.Users.Domain.csproj" />
    <ProjectReference Include="..\..\..\..\framework\SufiChain.SufiAbp.EntityFrameworkCore\SufiChain.SufiAbp.EntityFrameworkCore.csproj" />
  </ItemGroup>

</Project>
