<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>SufiChain.SufiAbp.TextTemplating</RootNamespace>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>SufiChain.SufiAbp.TextTemplating</PackageId>
    <Description>Sufi Platform text templating abstractions and implementations.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.Localization" Version="$(AbpVersion)" />
    <ProjectReference Include="../SufiChain.SufiAbp.UI.Domain.Shared/SufiChain.SufiAbp.UI.Domain.Shared.csproj" />
    <ProjectReference Include="..\SufiChain.SufiAbp.Core\SufiChain.SufiAbp.Core.csproj" />
    <PackageReference Include="Volo.Abp.VirtualFileSystem" Version="$(AbpVersion)" />
  </ItemGroup>

</Project>
