using SufiChain.SufiPlatform.CLI.ProjectBuilding.Pipeline;
using System.Text;

namespace SufiChain.SufiPlatform.CLI.ProjectBuilding.Steps;

/// <summary>
/// Creates a .gitignore file for the generated solution.
/// </summary>
public class CreateGitIgnoreStep : ProjectBuildPipelineStep
{
    public override string Description => "Creating .gitignore...";

    public override Task ExecuteAsync(ProjectBuildContext context)
    {
        // Only create if it doesn't exist
        if (!context.Files.ContainsKey(".gitignore"))
        {
            context.Files[".gitignore"] = Encoding.UTF8.GetBytes(GitIgnoreContent);
        }
        return Task.CompletedTask;
    }

    private const string GitIgnoreContent = @"## Ignore Visual Studio temporary files, build results, and
## files generated by popular Visual Studio add-ons.

# Build results
[Dd]ebug/
[Rr]elease/
x64/
x86/
bld/
[Bb]in/
[Oo]bj/
[Ll]og/
[Ll]ogs/

# Visual Studio files
.vs/
*.suo
*.user
*.userosscache
*.sln.docstates
*.rsuser

# JetBrains Rider
.idea/
*.sln.iml

# VS Code
.vscode/
!.vscode/settings.json
!.vscode/tasks.json
!.vscode/launch.json
!.vscode/extensions.json

# NuGet
*.nupkg
**/[Pp]ackages/*
!**/[Pp]ackages/build/
*.nuget.props
*.nuget.targets

# Node.js
node_modules/
npm-debug.log
yarn-error.log
yarn.lock
package-lock.json

# Build outputs
*.dll
*.exe
*.pdb

# Temporary files
*.tmp
*~
*.swp

# OS generated files
.DS_Store
.DS_Store?
._*
.Spotlight-V100
.Trashes
ehthumbs.db
Thumbs.db

# Application specific
**/wwwroot/libs/
**/wwwroot/dist/
appsettings.secrets.json
tempkey.*

# Test results
TestResults/
*.trx
";
}
