<Project Sdk="Microsoft.NET.Sdk">


  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>SufiChain.SufiAbp.Users.MongoDB</AssemblyName>
    <PackageId>SufiChain.SufiAbp.Users.MongoDB</PackageId>
    <RootNamespace>SufiChain.SufiAbp.Users</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SufiChain.SufiAbp.Users.Domain\SufiChain.SufiAbp.Users.Domain.csproj" />
    <PackageReference Include="Volo.Abp.MongoDB" Version="$(AbpVersion)" />
  </ItemGroup>

</Project>
