<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>SufiChain.SufiAbp.OpenIddict</RootNamespace>
    <PackageId>SufiChain.SufiAbp.OpenIddict.MongoDB</PackageId>
    <Description>MongoDB integration for SufiAbp OpenIddict.</Description>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Volo.Abp.MongoDB" Version="$(AbpVersion)" />
    <ProjectReference Include="..\SufiChain.SufiAbp.OpenIddict.Domain\SufiChain.SufiAbp.OpenIddict.Domain.csproj" />
  </ItemGroup>
</Project>
