<TEMPLATE-REMOVE IF-NOT="db:mongodb">
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>MyCompanyName.MyProjectName</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  
  <ItemGroup>
    <ProjectReference Include="..\MyCompanyName.MyProjectName.Domain\MyCompanyName.MyProjectName.Domain.csproj" />
  </ItemGroup>

  <TEMPLATE-REMOVE>
  <ItemGroup>
    <ProjectReference Include="..\..\..\..\..\src\framework\SufiChain.SufiPlatform.Core\SufiChain.SufiPlatform.Core.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\permissions\src\SufiChain.SufiPlatform.Permissions.MongoDB\SufiChain.SufiPlatform.Permissions.MongoDB.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\settings\src\SufiChain.SufiPlatform.Settings.MongoDB\SufiChain.SufiPlatform.Settings.MongoDB.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\features\src\SufiChain.SufiPlatform.Features.MongoDB\SufiChain.SufiPlatform.Features.MongoDB.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\audit-logging\src\SufiChain.SufiPlatform.AuditLogging.MongoDB\SufiChain.SufiPlatform.AuditLogging.MongoDB.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\jobs\src\SufiChain.SufiPlatform.BackgroundJobs.MongoDB\SufiChain.SufiPlatform.BackgroundJobs.MongoDB.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\identity\src\SufiChain.SufiPlatform.Identity.MongoDB\SufiChain.SufiPlatform.Identity.MongoDB.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\users\src\SufiChain.SufiPlatform.Users.MongoDB\SufiChain.SufiPlatform.Users.MongoDB.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\tenants\src\SufiChain.SufiPlatform.Tenants.MongoDB\SufiChain.SufiPlatform.Tenants.MongoDB.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\openiddict\src\SufiChain.SufiPlatform.OpenIddict.MongoDB\SufiChain.SufiPlatform.OpenIddict.MongoDB.csproj" />
    
    <ProjectReference Include="..\..\..\..\..\modules\blob-database\src\SufiChain.SufiPlatform.BlobDatabase.MongoDB\SufiChain.SufiPlatform.BlobDatabase.MongoDB.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\file-manager\src\SufiChain.SufiPlatform.FileManager.MongoDB\SufiChain.SufiPlatform.FileManager.MongoDB.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\localization\src\SufiChain.SufiPlatform.Localization.MongoDB\SufiChain.SufiPlatform.Localization.MongoDB.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\short-links\src\SufiChain.SufiPlatform.ShortLinks.MongoDB\SufiChain.SufiPlatform.ShortLinks.MongoDB.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\ai\src\SufiChain.SufiPlatform.SufiAI.MongoDB\SufiChain.SufiPlatform.SufiAI.MongoDB.csproj" />
  </ItemGroup>
  </TEMPLATE-REMOVE>

  <TEMPLATE-ONLY>
  <ItemGroup>
    <PackageReference Include="SufiChain.SufiPlatform.Core" Version="$(SufiVersion)" />
    <PackageReference Include="SufiChain.SufiPlatform.Permissions.MongoDB" Version="$(SufiVersion)" />
    <PackageReference Include="SufiChain.SufiPlatform.Settings.MongoDB" Version="$(SufiVersion)" />
    <PackageReference Include="SufiChain.SufiPlatform.Features.MongoDB" Version="$(SufiVersion)" />
    <PackageReference Include="SufiChain.SufiPlatform.AuditLogging.MongoDB" Version="$(SufiVersion)" />
    <PackageReference Include="SufiChain.SufiPlatform.BackgroundJobs.MongoDB" Version="$(SufiVersion)" />
    <PackageReference Include="SufiChain.SufiPlatform.Identity.MongoDB" Version="$(SufiVersion)" />
    <PackageReference Include="SufiChain.SufiPlatform.Users.MongoDB" Version="$(SufiVersion)" />
    <PackageReference Include="SufiChain.SufiPlatform.Tenants.MongoDB" Version="$(SufiVersion)" />
    <PackageReference Include="SufiChain.SufiPlatform.OpenIddict.MongoDB" Version="$(SufiVersion)" />
    <PackageReference Include="SufiChain.SufiPlatform.BlobDatabase.MongoDB" Version="$(SufiVersion)" />
    <PackageReference Include="SufiChain.SufiPlatform.FileManager.MongoDB" Version="$(SufiVersion)" />
    <PackageReference Include="SufiChain.SufiPlatform.Localization.MongoDB" Version="$(SufiVersion)" />
    <PackageReference Include="SufiChain.SufiPlatform.ShortLinks.MongoDB" Version="$(SufiVersion)" />
    <PackageReference Include="SufiChain.SufiPlatform.SufiAI.MongoDB" Version="$(SufiVersion)" />
  </ItemGroup>
  </TEMPLATE-ONLY>

</Project>
</TEMPLATE-REMOVE>
