<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>SufiChain.SufiAbp.AutoMapper</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="$(AutoMapperVersion)"/>
    <PackageReference Include="Volo.Abp.Autofac" Version="$(AbpVersion)"/>

  </ItemGroup>
</Project>
