<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>SufiChain.SufiAbp.AI</RootNamespace>
    <PackageId>SufiChain.SufiAbp.AI.Domain</PackageId>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\framework\SufiChain.SufiAbp.Ddd.Application.Contracts\SufiChain.SufiAbp.Ddd.Application.Contracts.csproj" />
    <PackageReference Include="Volo.Abp.Ddd.Domain" Version="$(AbpVersion)" />
    <ProjectReference Include="..\..\..\..\framework\SufiChain.SufiAbp.AI\SufiChain.SufiAbp.AI.csproj" />
    <ProjectReference Include="..\..\..\file-manager\src\SufiChain.SufiAbp.FileManager.Domain\SufiChain.SufiAbp.FileManager.Domain.csproj" />
    <ProjectReference Include="..\..\..\file-manager\src\SufiChain.SufiAbp.FileManager.Domain.Shared\SufiChain.SufiAbp.FileManager.Domain.Shared.csproj" />
    <ProjectReference Include="..\..\..\file-manager\src\SufiChain.SufiAbp.FileManager.Application.Contracts\SufiChain.SufiAbp.FileManager.Application.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SufiChain.SufiAbp.AI.Domain.Shared\SufiChain.SufiAbp.AI.Domain.Shared.csproj" />
  </ItemGroup>
</Project>
