<?xml version="1.0" encoding="utf-16"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>MyCompanyName.MyProjectName</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <TEMPLATE-REMOVE>
    <ItemGroup>
      <ProjectReference Include="..\..\..\..\..\framework\SufiChain.SufiPlatform.Core\SufiChain.SufiPlatform.Core.csproj" />
      <ProjectReference Include="..\..\..\..\..\framework\SufiChain.SufiPlatform.Authorization\SufiChain.SufiPlatform.Authorization.csproj" />
      <ProjectReference Include="..\..\..\..\..\modules\tenants\src\SufiChain.SufiPlatform.Tenants.Application.Contracts\SufiChain.SufiPlatform.Tenants.Application.Contracts.csproj" />
      <ProjectReference Include="..\MyCompanyName.MyProjectName.Domain.Shared\MyCompanyName.MyProjectName.Domain.Shared.csproj" />
      <ProjectReference Include="..\..\..\..\..\modules\account\src\SufiChain.SufiPlatform.Account.Application.Contracts\SufiChain.SufiPlatform.Account.Application.Contracts.csproj" />
      <ProjectReference Include="..\..\..\..\..\modules\permissions\src\SufiChain.SufiPlatform.Permissions.Application.Contracts\SufiChain.SufiPlatform.Permissions.Application.Contracts.csproj" />
      <ProjectReference Include="..\..\..\..\..\modules\features\src\SufiChain.SufiPlatform.Features.Application.Contracts\SufiChain.SufiPlatform.Features.Application.Contracts.csproj" />
      <ProjectReference Include="..\..\..\..\..\modules\settings\src\SufiChain.SufiPlatform.Settings.Application.Contracts\SufiChain.SufiPlatform.Settings.Application.Contracts.csproj" />
      <ProjectReference Include="..\..\..\..\..\modules\identity\src\SufiChain.SufiPlatform.Identity.Application.Contracts\SufiChain.SufiPlatform.Identity.Application.Contracts.csproj" />
    </ItemGroup>
  </TEMPLATE-REMOVE>
  <TEMPLATE-ONLY>
    <ItemGroup>
      <PackageReference Include="SufiChain.SufiPlatform.Core" Version="$(SufiVersion)" />
      <PackageReference Include="SufiChain.SufiPlatform.Authorization" Version="$(SufiVersion)" />
      <PackageReference Include="SufiChain.SufiPlatform.Tenants.Application.Contracts" Version="$(SufiVersion)" />
      <ProjectReference Include="..\MyCompanyName.MyProjectName.Domain.Shared\MyCompanyName.MyProjectName.Domain.Shared.csproj" />
      <PackageReference Include="SufiChain.SufiPlatform.Calendar.Application.Contracts" Version="$(SufiVersion)" />
      <PackageReference Include="SufiChain.SufiPlatform.Localization.Application.Contracts" Version="$(SufiVersion)" />
      <PackageReference Include="SufiChain.SufiPlatform.SufiAI.Application.Contracts" Version="$(SufiVersion)" />
      <PackageReference Include="SufiChain.SufiPlatform.FileManager.Application.Contracts" Version="$(SufiVersion)" />
      <PackageReference Include="SufiChain.SufiPlatform.Account.Application.Contracts" Version="$(SufiVersion)" />
      <PackageReference Include="SufiChain.SufiPlatform.Permissions.Application.Contracts" Version="$(SufiVersion)" />
      <PackageReference Include="SufiChain.SufiPlatform.Features.Application.Contracts" Version="$(SufiVersion)" />
      <PackageReference Include="SufiChain.SufiPlatform.Settings.Application.Contracts" Version="$(SufiVersion)" />
      <PackageReference Include="SufiChain.SufiPlatform.Identity.Application.Contracts" Version="$(SufiVersion)" />
    </ItemGroup>
  </TEMPLATE-ONLY>
  <TEMPLATE-REMOVE>
    <ItemGroup>
    <PackageReference Include="Volo.Abp.ObjectExtending" Version="$(AbpVersion)" />
  </ItemGroup>
  </TEMPLATE-REMOVE>
  <TEMPLATE-ONLY>
    <ItemGroup>
      <PackageReference Include="Volo.Abp.ObjectExtending" Version="$(AbpVersion)" />
    </ItemGroup>
  </TEMPLATE-ONLY>
</Project>
