<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>SufiChain.SufiAbp.AspNetCore.Authentication.Server</RootNamespace>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>SufiChain.SufiAbp.AspNetCore.Authentication.Server</PackageId>
    <Description>Server-side authentication for Sufi Platform Blazor applications using OIDC.</Description>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\modules\identity\src\SufiChain.SufiAbp.Identity.Domain\SufiChain.SufiAbp.Identity.Domain.csproj" />
    <ProjectReference Include="..\..\modules\account\src\SufiChain.SufiAbp.Account.Application.Contracts\SufiChain.SufiAbp.Account.Application.Contracts.csproj" />
    <ProjectReference Include="..\SufiChain.SufiAbp.AspNetCore.Authentication.Abstractions\SufiChain.SufiAbp.AspNetCore.Authentication.Abstractions.csproj" />
    <ProjectReference Include="..\SufiChain.SufiAbp.AspNetCore.Mvc\SufiChain.SufiAbp.AspNetCore.Mvc.csproj" />
    <ProjectReference Include="..\SufiChain.SufiAbp.UI.Abstractions\SufiChain.SufiAbp.UI.Abstractions.csproj" />
  </ItemGroup>

</Project>
