<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.1;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>SufiChain.SufiPlatform.Features</RootNamespace>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>SufiChain.SufiPlatform.Features</PackageId>
    <Description>Sufi Platform feature management abstractions and module feature name constants.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.Localization" Version="$(AbpVersion)" />
    <ProjectReference Include="../SufiChain.SufiPlatform.UI.Domain.Shared/SufiChain.SufiPlatform.UI.Domain.Shared.csproj" />
    <PackageReference Include="Volo.Abp.Features" Version="$(AbpVersion)"/>
  </ItemGroup>

</Project>
