  <Project>

        <ItemGroup Condition="Exists('$(MSBuildThisFileDirectory)README.md')">
            <None Include="$(MSBuildThisFileDirectory)README.md" Pack="true" PackagePath="\" Visible="false" />
        </ItemGroup>

        <ItemGroup>
            <PackageReference Include="ConfigureAwait.Fody" Version="$(ConfigureAwaitFodyVersion)" PrivateAssets="All"/>
            <PackageReference Include="Fody" Version="$(FodyVersion)">
                <PrivateAssets>All</PrivateAssets>
                <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
            </PackageReference>
        </ItemGroup>

        <Target Name="NoWarnOnRazorViewImportedTypeConflicts" BeforeTargets="RazorCoreCompile">
            <PropertyGroup>
                <NoWarn>$(NoWarn);0436</NoWarn>
            </PropertyGroup>
        </Target>

        <ItemGroup>
            <None Remove="**\*.abppkg"/>
            <None Remove="**\*.abppkg.analyze.json"/>
            <Content Remove="$(UserProfile)\.nuget\packages\*\*\contentFiles\any\*\*.abppkg*"/>
        </ItemGroup>
</Project>
