<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>MyCompanyName.MyProjectName</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  
  <ItemGroup>
    <ProjectReference Include="..\MyCompanyName.MyProjectName.Application.Contracts\MyCompanyName.MyProjectName.Application.Contracts.csproj" />
    <ProjectReference Include="..\MyCompanyName.MyProjectName.Domain\MyCompanyName.MyProjectName.Domain.csproj" />
  </ItemGroup>

  <TEMPLATE-REMOVE>
  <ItemGroup>
    <ProjectReference Include="..\..\..\..\..\src\framework\SufiChain.SufiAbp.Core\SufiChain.SufiAbp.Core.csproj" />
    <ProjectReference Include="..\..\..\..\..\src\framework\SufiChain.SufiAbp.Data\SufiChain.SufiAbp.Data.csproj" />
    <PackageReference Include="Volo.Abp.EntityFrameworkCore.SqlServer" Version="$(AbpVersion)" />
    <PackageReference Include="Volo.Abp.EntityFrameworkCore.PostgreSql" Version="$(AbpVersion)" />
    <PackageReference Include="Volo.Abp.EntityFrameworkCore.MySQL" Version="$(AbpVersion)" />
    <PackageReference Include="Volo.Abp.EntityFrameworkCore.Sqlite" Version="$(AbpVersion)" />
  </ItemGroup>
  </TEMPLATE-REMOVE>

  <TEMPLATE-ONLY>
  <ItemGroup>
    <PackageReference Include="SufiChain.SufiAbp.Core" Version="$(SufiVersion)" />
    <PackageReference Include="SufiChain.SufiAbp.Data" Version="$(SufiVersion)" />
    <TEMPLATE-REMOVE IF-NOT="efp:sqlserver">
    <PackageReference Include="Volo.Abp.EntityFrameworkCore.SqlServer" Version="$(AbpVersion)" />
    </TEMPLATE-REMOVE>
    <TEMPLATE-REMOVE IF-NOT="efp:postgresql">
    <PackageReference Include="Volo.Abp.EntityFrameworkCore.PostgreSql" Version="$(AbpVersion)" />
    </TEMPLATE-REMOVE>
    <TEMPLATE-REMOVE IF-NOT="efp:mysql">
    <PackageReference Include="Volo.Abp.EntityFrameworkCore.MySQL" Version="$(AbpVersion)" />
    </TEMPLATE-REMOVE>
    <TEMPLATE-REMOVE IF-NOT="efp:sqlite">
    <PackageReference Include="Volo.Abp.EntityFrameworkCore.Sqlite" Version="$(AbpVersion)" />
    </TEMPLATE-REMOVE>
  </ItemGroup>
  </TEMPLATE-ONLY>

  <ItemGroup>

    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="$(MicrosoftEntityFrameworkCoreVersion)" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="$(MicrosoftEntityFrameworkCoreVersion)">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <TEMPLATE-REMOVE>
  <ItemGroup>
    <ProjectReference Include="..\..\..\..\..\modules\permission-management\src\SufiChain.SufiAbp.PermissionManagement.EntityFrameworkCore\SufiChain.SufiAbp.PermissionManagement.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\setting-management\src\SufiChain.SufiAbp.SettingManagement.EntityFrameworkCore\SufiChain.SufiAbp.SettingManagement.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\feature-management\src\SufiChain.SufiAbp.FeatureManagement.EntityFrameworkCore\SufiChain.SufiAbp.FeatureManagement.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\audit-logging\src\SufiChain.SufiAbp.AuditLogging.EntityFrameworkCore\SufiChain.SufiAbp.AuditLogging.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\background-jobs\src\SufiChain.SufiAbp.BackgroundJobs.EntityFrameworkCore\SufiChain.SufiAbp.BackgroundJobs.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\identity\src\SufiChain.SufiAbp.Identity.EntityFrameworkCore\SufiChain.SufiAbp.Identity.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\users\src\SufiChain.SufiAbp.Users.EntityFrameworkCore\SufiChain.SufiAbp.Users.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\tenant-management\src\SufiChain.SufiAbp.TenantManagement.EntityFrameworkCore\SufiChain.SufiAbp.TenantManagement.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\openiddict\src\SufiChain.SufiAbp.OpenIddict.EntityFrameworkCore\SufiChain.SufiAbp.OpenIddict.EntityFrameworkCore.csproj" />
    
    <ProjectReference Include="..\..\..\..\..\modules\blob-storing-database\src\SufiChain.SufiAbp.BlobStoring.Database.EntityFrameworkCore\SufiChain.SufiAbp.BlobStoring.Database.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\file-manager\src\SufiChain.SufiAbp.FileManager.EntityFrameworkCore\SufiChain.SufiAbp.FileManager.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\localization-management\src\SufiChain.SufiAbp.LocalizationManagement.EntityFrameworkCore\SufiChain.SufiAbp.LocalizationManagement.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\short-link-generator\src\SufiChain.SufiAbp.ShortLinkGenerator.EntityFrameworkCore\SufiChain.SufiAbp.ShortLinkGenerator.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\calendar\src\SufiChain.SufiAbp.Calendar.EntityFrameworkCore\SufiChain.SufiAbp.Calendar.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\tags-management\src\SufiChain.SufiAbp.TagsManagement.EntityFrameworkCore\SufiChain.SufiAbp.TagsManagement.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\menu-management\src\SufiChain.SufiAbp.MenuManagement.EntityFrameworkCore\SufiChain.SufiAbp.MenuManagement.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\ai\src\SufiChain.SufiAbp.AI.EntityFrameworkCore\SufiChain.SufiAbp.AI.EntityFrameworkCore.csproj" />
  </ItemGroup>
  </TEMPLATE-REMOVE>

  <TEMPLATE-ONLY>
  <ItemGroup>
    <PackageReference Include="SufiChain.SufiAbp.PermissionManagement.EntityFrameworkCore" Version="$(SufiVersion)" />
    <PackageReference Include="SufiChain.SufiAbp.SettingManagement.EntityFrameworkCore" Version="$(SufiVersion)" />
    <PackageReference Include="SufiChain.SufiAbp.FeatureManagement.EntityFrameworkCore" Version="$(SufiVersion)" />
    <PackageReference Include="SufiChain.SufiAbp.AuditLogging.EntityFrameworkCore" Version="$(SufiVersion)" />
    <PackageReference Include="SufiChain.SufiAbp.BackgroundJobs.EntityFrameworkCore" Version="$(SufiVersion)" />
    <PackageReference Include="SufiChain.SufiAbp.Identity.EntityFrameworkCore" Version="$(SufiVersion)" />
    <PackageReference Include="SufiChain.SufiAbp.Users.EntityFrameworkCore" Version="$(SufiVersion)" />
    <PackageReference Include="SufiChain.SufiAbp.TenantManagement.EntityFrameworkCore" Version="$(SufiVersion)" />
    <PackageReference Include="SufiChain.SufiAbp.OpenIddict.EntityFrameworkCore" Version="$(SufiVersion)" />
    <PackageReference Include="SufiChain.SufiAbp.BlobStoring.Database.EntityFrameworkCore" Version="$(SufiVersion)" />
    <PackageReference Include="SufiChain.SufiAbp.FileManager.EntityFrameworkCore" Version="$(SufiVersion)" />
    <PackageReference Include="SufiChain.SufiAbp.LocalizationManagement.EntityFrameworkCore" Version="$(SufiVersion)" />
    <PackageReference Include="SufiChain.SufiAbp.ShortLinkGenerator.EntityFrameworkCore" Version="$(SufiVersion)" />
    <PackageReference Include="SufiChain.SufiAbp.Calendar.EntityFrameworkCore" Version="$(SufiVersion)" />
    <PackageReference Include="SufiChain.SufiAbp.TagsManagement.EntityFrameworkCore" Version="$(SufiVersion)" />
    <PackageReference Include="SufiChain.SufiAbp.MenuManagement.EntityFrameworkCore" Version="$(SufiVersion)" />
    <PackageReference Include="SufiChain.SufiAbp.AI.EntityFrameworkCore" Version="$(SufiVersion)" />
  </ItemGroup>
  </TEMPLATE-ONLY>

</Project>
