<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>MyCompanyName.MyProjectName</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  
  <ItemGroup>
    <ProjectReference Include="..\MyCompanyName.MyProjectName.Application.Contracts\MyCompanyName.MyProjectName.Application.Contracts.csproj" />
    <ProjectReference Include="..\MyCompanyName.MyProjectName.Domain\MyCompanyName.MyProjectName.Domain.csproj" />
  </ItemGroup>

  <TEMPLATE-REMOVE>
  <ItemGroup>
    <ProjectReference Include="..\..\..\..\..\src\framework\SufiChain.SufiPlatform.Core\SufiChain.SufiPlatform.Core.csproj" />
    <ProjectReference Include="..\..\..\..\..\src\framework\SufiChain.SufiPlatform.Data\SufiChain.SufiPlatform.Data.csproj" />
    <PackageReference Include="Volo.Abp.EntityFrameworkCore.SqlServer" Version="$(AbpVersion)" />
    <PackageReference Include="Volo.Abp.EntityFrameworkCore.PostgreSql" Version="$(AbpVersion)" />
    <PackageReference Include="Volo.Abp.EntityFrameworkCore.MySQL" Version="$(AbpVersion)" />
    <PackageReference Include="Volo.Abp.EntityFrameworkCore.Sqlite" Version="$(AbpVersion)" />
  </ItemGroup>
  </TEMPLATE-REMOVE>

  <TEMPLATE-ONLY>
  <ItemGroup>
    <PackageReference Include="SufiChain.SufiPlatform.Core" Version="$(SufiVersion)" />
    <PackageReference Include="SufiChain.SufiPlatform.Data" Version="$(SufiVersion)" />
    <TEMPLATE-REMOVE IF-NOT="efp:sqlserver">
    <PackageReference Include="Volo.Abp.EntityFrameworkCore.SqlServer" Version="$(AbpVersion)" />
    </TEMPLATE-REMOVE>
    <TEMPLATE-REMOVE IF-NOT="efp:postgresql">
    <PackageReference Include="Volo.Abp.EntityFrameworkCore.PostgreSql" Version="$(AbpVersion)" />
    </TEMPLATE-REMOVE>
    <TEMPLATE-REMOVE IF-NOT="efp:mysql">
    <PackageReference Include="Volo.Abp.EntityFrameworkCore.MySQL" Version="$(AbpVersion)" />
    </TEMPLATE-REMOVE>
    <TEMPLATE-REMOVE IF-NOT="efp:sqlite">
    <PackageReference Include="Volo.Abp.EntityFrameworkCore.Sqlite" Version="$(AbpVersion)" />
    </TEMPLATE-REMOVE>
  </ItemGroup>
  </TEMPLATE-ONLY>

  <ItemGroup>

    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="$(MicrosoftEntityFrameworkCoreVersion)" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="$(MicrosoftEntityFrameworkCoreVersion)">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <TEMPLATE-REMOVE>
  <ItemGroup>
    <ProjectReference Include="..\..\..\..\..\modules\permissions\src\SufiChain.SufiPlatform.Permissions.EntityFrameworkCore\SufiChain.SufiPlatform.Permissions.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\settings\src\SufiChain.SufiPlatform.Settings.EntityFrameworkCore\SufiChain.SufiPlatform.Settings.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\features\src\SufiChain.SufiPlatform.Features.EntityFrameworkCore\SufiChain.SufiPlatform.Features.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\audit-logging\src\SufiChain.SufiPlatform.AuditLogging.EntityFrameworkCore\SufiChain.SufiPlatform.AuditLogging.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\jobs\src\SufiChain.SufiPlatform.BackgroundJobs.EntityFrameworkCore\SufiChain.SufiPlatform.BackgroundJobs.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\identity\src\SufiChain.SufiPlatform.Identity.EntityFrameworkCore\SufiChain.SufiPlatform.Identity.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\users\src\SufiChain.SufiPlatform.Users.EntityFrameworkCore\SufiChain.SufiPlatform.Users.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\tenants\src\SufiChain.SufiPlatform.Tenants.EntityFrameworkCore\SufiChain.SufiPlatform.Tenants.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\openiddict\src\SufiChain.SufiPlatform.OpenIddict.EntityFrameworkCore\SufiChain.SufiPlatform.OpenIddict.EntityFrameworkCore.csproj" />
    
    <ProjectReference Include="..\..\..\..\..\modules\blob-database\src\SufiChain.SufiPlatform.BlobDatabase.EntityFrameworkCore\SufiChain.SufiPlatform.BlobDatabase.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\file-manager\src\SufiChain.SufiPlatform.FileManager.EntityFrameworkCore\SufiChain.SufiPlatform.FileManager.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\localization\src\SufiChain.SufiPlatform.Localization.EntityFrameworkCore\SufiChain.SufiPlatform.Localization.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\short-links\src\SufiChain.SufiPlatform.ShortLinks.EntityFrameworkCore\SufiChain.SufiPlatform.ShortLinks.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\calendar\src\SufiChain.SufiPlatform.Calendar.EntityFrameworkCore\SufiChain.SufiPlatform.Calendar.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\tags\src\SufiChain.SufiPlatform.Tags.EntityFrameworkCore\SufiChain.SufiPlatform.Tags.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\menus\src\SufiChain.SufiPlatform.Menus.EntityFrameworkCore\SufiChain.SufiPlatform.Menus.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\ai\src\SufiChain.SufiPlatform.SufiAI.EntityFrameworkCore\SufiChain.SufiPlatform.SufiAI.EntityFrameworkCore.csproj" />
  </ItemGroup>
  </TEMPLATE-REMOVE>

  <TEMPLATE-ONLY>
  <ItemGroup>
    <PackageReference Include="SufiChain.SufiPlatform.Permissions.EntityFrameworkCore" Version="$(SufiVersion)" />
    <PackageReference Include="SufiChain.SufiPlatform.Settings.EntityFrameworkCore" Version="$(SufiVersion)" />
    <PackageReference Include="SufiChain.SufiPlatform.Features.EntityFrameworkCore" Version="$(SufiVersion)" />
    <PackageReference Include="SufiChain.SufiPlatform.AuditLogging.EntityFrameworkCore" Version="$(SufiVersion)" />
    <PackageReference Include="SufiChain.SufiPlatform.BackgroundJobs.EntityFrameworkCore" Version="$(SufiVersion)" />
    <PackageReference Include="SufiChain.SufiPlatform.Identity.EntityFrameworkCore" Version="$(SufiVersion)" />
    <PackageReference Include="SufiChain.SufiPlatform.Users.EntityFrameworkCore" Version="$(SufiVersion)" />
    <PackageReference Include="SufiChain.SufiPlatform.Tenants.EntityFrameworkCore" Version="$(SufiVersion)" />
    <PackageReference Include="SufiChain.SufiPlatform.OpenIddict.EntityFrameworkCore" Version="$(SufiVersion)" />
    <PackageReference Include="SufiChain.SufiPlatform.BlobDatabase.EntityFrameworkCore" Version="$(SufiVersion)" />
    <PackageReference Include="SufiChain.SufiPlatform.FileManager.EntityFrameworkCore" Version="$(SufiVersion)" />
    <PackageReference Include="SufiChain.SufiPlatform.Localization.EntityFrameworkCore" Version="$(SufiVersion)" />
    <PackageReference Include="SufiChain.SufiPlatform.ShortLinks.EntityFrameworkCore" Version="$(SufiVersion)" />
    <PackageReference Include="SufiChain.SufiPlatform.Calendar.EntityFrameworkCore" Version="$(SufiVersion)" />
    <PackageReference Include="SufiChain.SufiPlatform.Tags.EntityFrameworkCore" Version="$(SufiVersion)" />
    <PackageReference Include="SufiChain.SufiPlatform.Menus.EntityFrameworkCore" Version="$(SufiVersion)" />
    <PackageReference Include="SufiChain.SufiPlatform.SufiAI.EntityFrameworkCore" Version="$(SufiVersion)" />
  </ItemGroup>
  </TEMPLATE-ONLY>

</Project>
