<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net10.0</TargetFramework><Nullable>enable</Nullable><RootNamespace>SufiChain.SufiPlatform.Menus</RootNamespace></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../../framework/SufiChain.SufiPlatform.Data/SufiChain.SufiPlatform.Data.csproj" />
    <PackageReference Include="Volo.Abp.Mapperly" Version="$(AbpVersion)" />
    <PackageReference Include="Volo.Abp.Caching" Version="$(AbpVersion)" />
    <ProjectReference Include="../../../../framework/SufiChain.SufiPlatform.Ddd.Application/SufiChain.SufiPlatform.Ddd.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../SufiChain.SufiPlatform.Menus.Domain/SufiChain.SufiPlatform.Menus.Domain.csproj" />
    <ProjectReference Include="../SufiChain.SufiPlatform.Menus.Application.Contracts/SufiChain.SufiPlatform.Menus.Application.Contracts.csproj" />
    <ProjectReference Include="../../../../framework/SufiChain.SufiPlatform.Features/SufiChain.SufiPlatform.Features.csproj" />
    <ProjectReference Include="../../../../../pro-modules/ai-hooshvare/src/SufiChain.SufiPlatform.SufiAI.Hooshvare.Application/SufiChain.SufiPlatform.SufiAI.Hooshvare.Application.csproj" />
  </ItemGroup>
</Project>
