<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>SufiChain.SufiAbp.OpenIddict</RootNamespace>
    <PackageId>SufiChain.SufiAbp.OpenIddict.Domain</PackageId>
    <Description>Domain layer for SufiAbp OpenIddict.</Description>
  </PropertyGroup>
  <ItemGroup>
    
    <PackageReference Include="Volo.Abp.Ddd.Domain" Version="$(AbpVersion)" />
    <PackageReference Include="Volo.Abp.Caching" Version="$(AbpVersion)" />
    <PackageReference Include="Volo.Abp.DistributedLocking.Abstractions" Version="$(AbpVersion)" />
    <PackageReference Include="Volo.Abp.Guids" Version="$(AbpVersion)" />
    <PackageReference Include="Volo.Abp.BackgroundWorkers" Version="$(AbpVersion)" />
    <PackageReference Include="Volo.Abp.Threading" Version="$(AbpVersion)" />
    <ProjectReference Include="../../../users/src/SufiChain.SufiAbp.Users/SufiChain.SufiAbp.Users.csproj" />
    <PackageReference Include="Volo.Abp.Mapperly" Version="$(AbpVersion)" />
    <ProjectReference Include="..\SufiChain.SufiAbp.OpenIddict.Domain.Shared\SufiChain.SufiAbp.OpenIddict.Domain.Shared.csproj" />
    <ProjectReference Include="../../../identity/src/SufiChain.SufiAbp.Identity.Domain/SufiChain.SufiAbp.Identity.Domain.csproj" />
  </ItemGroup>

</Project>
