<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>SufiChain.SufiAbp.FileManager.MarkdownEditor</RootNamespace>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>SufiChain.SufiAbp.FileManager.MarkdownEditor</PackageId>
    <Description>File manager markdown editor integration for Sufi Platform - media picker for SbMarkdownEditor.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="$(MicrosoftAspNetCoreComponentsWebVersion)" />
    <ProjectReference Include="../../../../framework/SufiChain.SufiAbp.AspNetCore.Components.Web/SufiChain.SufiAbp.AspNetCore.Components.Web.csproj" />
    <ProjectReference Include="..\SufiChain.SufiAbp.FileManager.RichTextEditor\SufiChain.SufiAbp.FileManager.RichTextEditor.csproj" />
  </ItemGroup>

</Project>
