<?xml version="1.0" encoding="utf-16"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>MyCompanyName.MyProjectName</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\MyCompanyName.MyProjectName.Domain\MyCompanyName.MyProjectName.Domain.csproj" />
    <ProjectReference Include="..\MyCompanyName.MyProjectName.Application.Contracts\MyCompanyName.MyProjectName.Application.Contracts.csproj" />
  </ItemGroup>
  <TEMPLATE-REMOVE>
    <ItemGroup>
      <ProjectReference Include="..\..\..\..\..\framework\SufiChain.SufiPlatform.Core\SufiChain.SufiPlatform.Core.csproj" />
      <ProjectReference Include="..\..\..\..\..\modules\identity\src\SufiChain.SufiPlatform.Identity.Application\SufiChain.SufiPlatform.Identity.Application.csproj" />
      <ProjectReference Include="..\..\..\..\..\modules\tenants\src\SufiChain.SufiPlatform.Tenants.Application\SufiChain.SufiPlatform.Tenants.Application.csproj" />
      <ProjectReference Include="..\..\..\..\..\modules\account\src\SufiChain.SufiPlatform.Account.Application\SufiChain.SufiPlatform.Account.Application.csproj" />
      <ProjectReference Include="..\..\..\..\..\modules\permissions\src\SufiChain.SufiPlatform.Permissions.Application\SufiChain.SufiPlatform.Permissions.Application.csproj" />
      <ProjectReference Include="..\..\..\..\..\modules\features\src\SufiChain.SufiPlatform.Features.Application\SufiChain.SufiPlatform.Features.Application.csproj" />
      <ProjectReference Include="..\..\..\..\..\modules\settings\src\SufiChain.SufiPlatform.Settings.Application\SufiChain.SufiPlatform.Settings.Application.csproj" />
      <ProjectReference Include="..\..\..\..\..\modules\short-links\src\SufiChain.SufiPlatform.ShortLinks.Application\SufiChain.SufiPlatform.ShortLinks.Application.csproj" />
      <ProjectReference Include="..\..\..\..\..\modules\tags\src\SufiChain.SufiPlatform.Tags.Application\SufiChain.SufiPlatform.Tags.Application.csproj" />
      <ProjectReference Include="..\..\..\..\..\modules\menus\src\SufiChain.SufiPlatform.Menus.Application\SufiChain.SufiPlatform.Menus.Application.csproj" />
    </ItemGroup>
  </TEMPLATE-REMOVE>
  <TEMPLATE-ONLY>
    <ItemGroup>
      <PackageReference Include="SufiChain.SufiPlatform.Core" Version="$(SufiVersion)" />
      <PackageReference Include="SufiChain.SufiPlatform.Calendar.Application" Version="$(SufiVersion)" />
      <PackageReference Include="SufiChain.SufiPlatform.Localization.Application" Version="$(SufiVersion)" />
      <PackageReference Include="SufiChain.SufiPlatform.SufiAI.Application" Version="$(SufiVersion)" />
      <PackageReference Include="SufiChain.SufiPlatform.FileManager.Application" Version="$(SufiVersion)" />
      <PackageReference Include="SufiChain.SufiPlatform.Identity.Application" Version="$(SufiVersion)" />
      <PackageReference Include="SufiChain.SufiPlatform.Tenants.Application" Version="$(SufiVersion)" />
      <PackageReference Include="SufiChain.SufiPlatform.Account.Application" Version="$(SufiVersion)" />
      <PackageReference Include="SufiChain.SufiPlatform.Permissions.Application" Version="$(SufiVersion)" />
      <PackageReference Include="SufiChain.SufiPlatform.Features.Application" Version="$(SufiVersion)" />
      <PackageReference Include="SufiChain.SufiPlatform.Settings.Application" Version="$(SufiVersion)" />
      <PackageReference Include="SufiChain.SufiPlatform.ShortLinks.Application" Version="$(SufiVersion)" />
      <PackageReference Include="SufiChain.SufiPlatform.Tags.Application" Version="$(SufiVersion)" />
      <PackageReference Include="SufiChain.SufiPlatform.Menus.Application" Version="$(SufiVersion)" />
    </ItemGroup>
  </TEMPLATE-ONLY>
</Project>
