<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>SufiChain.SufiPlatform.Permissions.OpenIddict</RootNamespace>
    <PackageId>SufiChain.SufiPlatform.Permissions.Domain.OpenIddict</PackageId>
    <Description>Permission management integration for Sufi OpenIddict.</Description>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\permissions\src\SufiChain.SufiPlatform.Permissions.Domain\SufiChain.SufiPlatform.Permissions.Domain.csproj" />
    <ProjectReference Include="..\SufiChain.SufiPlatform.OpenIddict.Domain.Shared\SufiChain.SufiPlatform.OpenIddict.Domain.Shared.csproj" />
  </ItemGroup>
</Project>
