<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>SufiChain.SufiAbp.BlobStoring.Database.MongoDB</RootNamespace>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>SufiChain.SufiAbp.BlobStoring.Database.MongoDB</PackageId>
    <Description>Sufi Platform database blob storage module MongoDB implementation.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../../../framework/SufiChain.SufiAbp.MongoDB/SufiChain.SufiAbp.MongoDB.csproj" />
    <ProjectReference Include="../SufiChain.SufiAbp.BlobStoring.Database.Domain/SufiChain.SufiAbp.BlobStoring.Database.Domain.csproj" />
  </ItemGroup>

</Project>
