<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <RootNamespace>SufiChain.SufiAbp.ShortLinkGenerator</RootNamespace>
        <PackageId>SufiChain.SufiAbp.ShortLinkGenerator.Application</PackageId>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="../../../../framework/SufiChain.SufiAbp.Ddd.Application/SufiChain.SufiAbp.Ddd.Application.csproj" />
    <PackageReference Include="Volo.Abp.Caching" Version="$(AbpVersion)" />
    <PackageReference Include="Volo.Abp.Mapperly" Version="$(AbpVersion)" />
    <ProjectReference Include="../../../setting-management/src/SufiChain.SufiAbp.SettingManagement.Domain/SufiChain.SufiAbp.SettingManagement.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\SufiChain.SufiAbp.ShortLinkGenerator.Domain\SufiChain.SufiAbp.ShortLinkGenerator.Domain.csproj" />
      <ProjectReference Include="..\SufiChain.SufiAbp.ShortLinkGenerator.Application.Contracts\SufiChain.SufiAbp.ShortLinkGenerator.Application.Contracts.csproj" />
    </ItemGroup>
</Project>
