<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<LangVersion>latest</LangVersion>
		<TargetFramework>net10.0</TargetFramework>
		<RootNamespace>MyCompanyName.MyProjectName</RootNamespace>
		<IsPackable>false</IsPackable>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="SufiChain.SufiAbp.Core" Version="$(SufiVersion)" />
		<PackageReference Include="SufiChain.SufiAbp.Http.Client" Version="$(SufiVersion)" />
		<PackageReference Include="SufiChain.SufiAbp.Calendar.Application.Contracts" Version="$(SufiVersion)" />
		<PackageReference Include="SufiChain.SufiAbp.LocalizationManagement.Application.Contracts" Version="$(SufiVersion)" />
		<PackageReference Include="SufiChain.SufiAbp.AI.Application.Contracts" Version="$(SufiVersion)" />
		<PackageReference Include="SufiChain.SufiAbp.FileManager.Application.Contracts" Version="$(SufiVersion)" />
		<ProjectReference Include="..\MyCompanyName.MyProjectName.Application.Contracts\MyCompanyName.MyProjectName.Application.Contracts.csproj" />
	</ItemGroup>
	<ItemGroup>
		<EmbeddedResource Include="**\*generate-proxy.json" />
		<Content Remove="**\*generate-proxy.json" />
	</ItemGroup>
</Project>
