<Project Sdk="Microsoft.NET.Sdk.Razor">


  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../../../framework/SufiChain.SufiAbp.AspNetCore.Components.Server.Theming/SufiChain.SufiAbp.AspNetCore.Components.Server.Theming.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SufiChain.SufiAbp.ShortLinkGenerator.Blazor\SufiChain.SufiAbp.ShortLinkGenerator.Blazor.csproj"/>
  </ItemGroup>

</Project>
