<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;netstandard2.1;net10.0</TargetFrameworks>

    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>SufiChain.SufiAbp.Data</RootNamespace>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>SufiChain.SufiAbp.Data</PackageId>
    <Description>Sufi Platform data configuration - removes Abp prefix from table/collection names.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.Core" Version="$(AbpVersion)" />
    <PackageReference Include="Volo.Abp.Data" Version="$(AbpVersion)" />
    <PackageReference Include="Volo.Abp.Settings" Version="$(AbpVersion)" />
  </ItemGroup>


</Project>
