<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>SufiChain.SufiPlatform.Menus.MongoDB</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Volo.Abp.MongoDB" Version="$(AbpVersion)" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../SufiChain.SufiPlatform.Menus.Domain/SufiChain.SufiPlatform.Menus.Domain.csproj" />
  </ItemGroup>
</Project>
