<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>SufiChain.SufiAbp.LocalizationManagement</RootNamespace>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>SufiChain.SufiAbp.LocalizationManagement.Domain</PackageId>
    <Description>Localization management module domain layer for Sufi Platform - entities, repositories, and domain services.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../../../framework/SufiChain.SufiAbp.Ddd.Domain/SufiChain.SufiAbp.Ddd.Domain.csproj" />
    <ProjectReference Include="..\..\..\setting-management\src\SufiChain.SufiAbp.SettingManagement.Domain\SufiChain.SufiAbp.SettingManagement.Domain.csproj" />
    <ProjectReference Include="..\SufiChain.SufiAbp.LocalizationManagement.Domain.Shared\SufiChain.SufiAbp.LocalizationManagement.Domain.Shared.csproj" />
  </ItemGroup>

</Project>
