<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup><LangVersion>latest</LangVersion>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>MyCompanyName.MyProjectName</RootNamespace>
    <GenerateEmbeddedFilesManifest>true</GenerateEmbeddedFilesManifest>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <!-- <TEMPLATE-REMOVE> -->
    <ItemGroup>
      <ProjectReference Include="..\..\..\..\..\src\framework\SufiChain.SufiAbp.Core\SufiChain.SufiAbp.Core.csproj" />
      <ProjectReference Include="..\..\..\..\..\src\framework\SufiChain.SufiAbp.UI.Domain.Shared\SufiChain.SufiAbp.UI.Domain.Shared.csproj" />
    </ItemGroup>
  <!-- </TEMPLATE-REMOVE> -->

	  <!-- <TEMPLATE-ONLY>
	  <ItemGroup>
	    <PackageReference Include="SufiChain.SufiAbp.Core" Version="$(SufiVersion)" />
	    <PackageReference Include="SufiChain.SufiAbp.UI.Domain.Shared" Version="$(SufiVersion)" />
	  </ItemGroup>
	  </TEMPLATE-ONLY> -->
	
	  
  
  <!-- <TEMPLATE-REMOVE> -->
	  <ItemGroup>
	    <!-- SufiAbp Infrastructure Modules - Domain.Shared -->
	    <ProjectReference Include="..\..\..\..\..\modules\calendar\src\SufiChain.SufiAbp.Calendar.Domain.Shared\SufiChain.SufiAbp.Calendar.Domain.Shared.csproj" />
	    <ProjectReference Include="..\..\..\..\..\modules\openiddict\src\SufiChain.SufiAbp.OpenIddict.Domain.Shared\SufiChain.SufiAbp.OpenIddict.Domain.Shared.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\permission-management\src\SufiChain.SufiAbp.PermissionManagement.Domain.Shared\SufiChain.SufiAbp.PermissionManagement.Domain.Shared.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\setting-management\src\SufiChain.SufiAbp.SettingManagement.Domain.Shared\SufiChain.SufiAbp.SettingManagement.Domain.Shared.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\feature-management\src\SufiChain.SufiAbp.FeatureManagement.Domain.Shared\SufiChain.SufiAbp.FeatureManagement.Domain.Shared.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\audit-logging\src\SufiChain.SufiAbp.AuditLogging.Domain.Shared\SufiChain.SufiAbp.AuditLogging.Domain.Shared.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\background-jobs\src\SufiChain.SufiAbp.BackgroundJobs.Domain.Shared\SufiChain.SufiAbp.BackgroundJobs.Domain.Shared.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\identity\src\SufiChain.SufiAbp.Identity.Domain.Shared\SufiChain.SufiAbp.Identity.Domain.Shared.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\tenant-management\src\SufiChain.SufiAbp.TenantManagement.Domain.Shared\SufiChain.SufiAbp.TenantManagement.Domain.Shared.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\short-link-generator\src\SufiChain.SufiAbp.ShortLinkGenerator.Domain.Shared\SufiChain.SufiAbp.ShortLinkGenerator.Domain.Shared.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\tags-management\src\SufiChain.SufiAbp.TagsManagement.Domain.Shared\SufiChain.SufiAbp.TagsManagement.Domain.Shared.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\menu-management\src\SufiChain.SufiAbp.MenuManagement.Domain.Shared\SufiChain.SufiAbp.MenuManagement.Domain.Shared.csproj" />
  </ItemGroup>
  <!-- </TEMPLATE-REMOVE> -->

<!-- <TEMPLATE-ONLY> -->
<!--
		  <ItemGroup>
		    <PackageReference Include="SufiChain.SufiAbp.Calendar.Domain.Shared" Version="$(SufiVersion)" />
	    <PackageReference Include="SufiChain.SufiAbp.LocalizationManagement.Domain.Shared" Version="$(SufiVersion)" />
	    <PackageReference Include="SufiChain.SufiAbp.AIManagement.Domain.Shared" Version="$(SufiVersion)" />
	    <PackageReference Include="SufiChain.SufiAbp.FileManager.Domain.Shared" Version="$(SufiVersion)" />
	    <PackageReference Include="SufiChain.SufiAbp.OpenIddict.Domain.Shared" Version="$(SufiVersion)" />
	    <PackageReference Include="SufiChain.SufiAbp.PermissionManagement.Domain.Shared" Version="$(SufiVersion)" />
     <PackageReference Include="SufiChain.SufiAbp.SettingManagement.Domain.Shared" Version="$(SufiVersion)" />
     <PackageReference Include="SufiChain.SufiAbp.FeatureManagement.Domain.Shared" Version="$(SufiVersion)" />
     <PackageReference Include="SufiChain.SufiAbp.AuditLogging.Domain.Shared" Version="$(SufiVersion)" />
     <PackageReference Include="SufiChain.SufiAbp.BackgroundJobs.Domain.Shared" Version="$(SufiVersion)" />
     <PackageReference Include="SufiChain.SufiAbp.Identity.Domain.Shared" Version="$(SufiVersion)" />
     <PackageReference Include="SufiChain.SufiAbp.TenantManagement.Domain.Shared" Version="$(SufiVersion)" />
     <PackageReference Include="SufiChain.SufiAbp.ShortLinkGenerator.Domain.Shared" Version="$(SufiVersion)" />
     <PackageReference Include="SufiChain.SufiAbp.TagsManagement.Domain.Shared" Version="$(SufiVersion)" />
     <PackageReference Include="SufiChain.SufiAbp.MenuManagement.Domain.Shared" Version="$(SufiVersion)" />
	  </ItemGroup>
	-->
<!-- </TEMPLATE-ONLY> -->

  <ItemGroup>
    <EmbeddedResource Include="Localization\DemoApp\*.json" />
    <Content Remove="Localization\DemoApp\*.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.FileProviders.Embedded" Version="$(MicrosoftExtensionsFileProvidersEmbeddedVersion)" />
  </ItemGroup>

</Project>
