<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup><LangVersion>latest</LangVersion>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>MyCompanyName.MyProjectName</RootNamespace>
    <GenerateEmbeddedFilesManifest>true</GenerateEmbeddedFilesManifest>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <!-- <TEMPLATE-REMOVE> -->
    <ItemGroup>
      <ProjectReference Include="..\..\..\..\..\src\framework\SufiChain.SufiPlatform.Core\SufiChain.SufiPlatform.Core.csproj" />
      <ProjectReference Include="..\..\..\..\..\src\framework\SufiChain.SufiPlatform.UI.Domain.Shared\SufiChain.SufiPlatform.UI.Domain.Shared.csproj" />
    </ItemGroup>
  <!-- </TEMPLATE-REMOVE> -->

	  <!-- <TEMPLATE-ONLY>
	  <ItemGroup>
	    <PackageReference Include="SufiChain.SufiPlatform.Core" Version="$(SufiVersion)" />
	    <PackageReference Include="SufiChain.SufiPlatform.UI.Domain.Shared" Version="$(SufiVersion)" />
	  </ItemGroup>
	  </TEMPLATE-ONLY> -->
	
	  
  
  <!-- <TEMPLATE-REMOVE> -->
	  <ItemGroup>
	    <!-- Sufi Platform Infrastructure Modules - Domain.Shared -->
	    <ProjectReference Include="..\..\..\..\..\modules\calendar\src\SufiChain.SufiPlatform.Calendar.Domain.Shared\SufiChain.SufiPlatform.Calendar.Domain.Shared.csproj" />
	    <ProjectReference Include="..\..\..\..\..\modules\openiddict\src\SufiChain.SufiPlatform.OpenIddict.Domain.Shared\SufiChain.SufiPlatform.OpenIddict.Domain.Shared.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\permissions\src\SufiChain.SufiPlatform.Permissions.Domain.Shared\SufiChain.SufiPlatform.Permissions.Domain.Shared.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\settings\src\SufiChain.SufiPlatform.Settings.Domain.Shared\SufiChain.SufiPlatform.Settings.Domain.Shared.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\features\src\SufiChain.SufiPlatform.Features.Domain.Shared\SufiChain.SufiPlatform.Features.Domain.Shared.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\audit-logging\src\SufiChain.SufiPlatform.AuditLogging.Domain.Shared\SufiChain.SufiPlatform.AuditLogging.Domain.Shared.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\jobs\src\SufiChain.SufiPlatform.BackgroundJobs.Domain.Shared\SufiChain.SufiPlatform.BackgroundJobs.Domain.Shared.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\identity\src\SufiChain.SufiPlatform.Identity.Domain.Shared\SufiChain.SufiPlatform.Identity.Domain.Shared.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\tenants\src\SufiChain.SufiPlatform.Tenants.Domain.Shared\SufiChain.SufiPlatform.Tenants.Domain.Shared.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\short-links\src\SufiChain.SufiPlatform.ShortLinks.Domain.Shared\SufiChain.SufiPlatform.ShortLinks.Domain.Shared.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\tags\src\SufiChain.SufiPlatform.Tags.Domain.Shared\SufiChain.SufiPlatform.Tags.Domain.Shared.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\menus\src\SufiChain.SufiPlatform.Menus.Domain.Shared\SufiChain.SufiPlatform.Menus.Domain.Shared.csproj" />
  </ItemGroup>
  <!-- </TEMPLATE-REMOVE> -->

<!-- <TEMPLATE-ONLY> -->
<!--
		  <ItemGroup>
		    <PackageReference Include="SufiChain.SufiPlatform.Calendar.Domain.Shared" Version="$(SufiVersion)" />
	    <PackageReference Include="SufiChain.SufiPlatform.Localization.Domain.Shared" Version="$(SufiVersion)" />
	    <PackageReference Include="SufiChain.SufiPlatform.SufiAI.Domain.Shared" Version="$(SufiVersion)" />
	    <PackageReference Include="SufiChain.SufiPlatform.FileManager.Domain.Shared" Version="$(SufiVersion)" />
	    <PackageReference Include="SufiChain.SufiPlatform.OpenIddict.Domain.Shared" Version="$(SufiVersion)" />
	    <PackageReference Include="SufiChain.SufiPlatform.Permissions.Domain.Shared" Version="$(SufiVersion)" />
     <PackageReference Include="SufiChain.SufiPlatform.Settings.Domain.Shared" Version="$(SufiVersion)" />
     <PackageReference Include="SufiChain.SufiPlatform.Features.Domain.Shared" Version="$(SufiVersion)" />
     <PackageReference Include="SufiChain.SufiPlatform.AuditLogging.Domain.Shared" Version="$(SufiVersion)" />
     <PackageReference Include="SufiChain.SufiPlatform.BackgroundJobs.Domain.Shared" Version="$(SufiVersion)" />
     <PackageReference Include="SufiChain.SufiPlatform.Identity.Domain.Shared" Version="$(SufiVersion)" />
     <PackageReference Include="SufiChain.SufiPlatform.Tenants.Domain.Shared" Version="$(SufiVersion)" />
     <PackageReference Include="SufiChain.SufiPlatform.ShortLinks.Domain.Shared" Version="$(SufiVersion)" />
     <PackageReference Include="SufiChain.SufiPlatform.Tags.Domain.Shared" Version="$(SufiVersion)" />
     <PackageReference Include="SufiChain.SufiPlatform.Menus.Domain.Shared" Version="$(SufiVersion)" />
	  </ItemGroup>
	-->
<!-- </TEMPLATE-ONLY> -->

  <ItemGroup>
    <EmbeddedResource Include="Localization\DemoApp\*.json" />
    <Content Remove="Localization\DemoApp\*.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.FileProviders.Embedded" Version="$(MicrosoftExtensionsFileProvidersEmbeddedVersion)" />
  </ItemGroup>

</Project>
