<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net10.0</TargetFramework><Nullable>enable</Nullable><RootNamespace>SufiChain.SufiPlatform.Menus</RootNamespace></PropertyGroup><ItemGroup><ProjectReference Include="../../../../framework/SufiChain.SufiPlatform.AspNetCore.Mvc/SufiChain.SufiPlatform.AspNetCore.Mvc.csproj" /></ItemGroup><ItemGroup><ProjectReference Include="../SufiChain.SufiPlatform.Menus.Application.Contracts/SufiChain.SufiPlatform.Menus.Application.Contracts.csproj" /></ItemGroup></Project>
