<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.1;net10.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <RootNamespace>SufiChain.SufiPlatform.Settings</RootNamespace>
    <GenerateEmbeddedFilesManifest>true</GenerateEmbeddedFilesManifest>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>SufiChain.SufiPlatform.Settings.Domain.Shared</PackageId>
    <Description>Setting management module domain shared layer for Sufi Platform - constants, enums, and localization.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\framework\SufiChain.SufiPlatform.UI.Domain.Shared\SufiChain.SufiPlatform.UI.Domain.Shared.csproj" />
    <ProjectReference Include="..\..\..\..\framework\SufiChain.SufiPlatform.Features\SufiChain.SufiPlatform.Features.csproj" />
    
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.FileProviders.Embedded" Version="$(MicrosoftExtensionsFileProvidersEmbeddedVersion)" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Localization\**\*.json" />
    <Content Remove="Localization\**\*.json" />
  </ItemGroup>

</Project>
