<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.1;net10.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <RootNamespace>SufiChain.SufiAbp.MenuManagement</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Volo.Abp.Http.Client" Version="$(AbpVersion)" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../SufiChain.SufiAbp.MenuManagement.Application.Contracts/SufiChain.SufiAbp.MenuManagement.Application.Contracts.csproj" />
  </ItemGroup>
</Project>
