<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.1;net10.0</TargetFrameworks>

    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>SufiChain.SufiPlatform.Data</RootNamespace>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>SufiChain.SufiPlatform.Data</PackageId>
    <Description>Sufi Platform data configuration - removes Abp prefix from table/collection names.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.Core" Version="$(AbpVersion)" />
    <PackageReference Include="Volo.Abp.Data" Version="$(AbpVersion)" />
    <PackageReference Include="Volo.Abp.Settings" Version="$(AbpVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\modules\settings\src\SufiChain.SufiPlatform.Settings.Application.Contracts\SufiChain.SufiPlatform.Settings.Application.Contracts.csproj" />
  </ItemGroup>


</Project>
