<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>SufiChain.SufiAbp.PermissionManagement</RootNamespace>
    <PackageId>SufiChain.SufiAbp.PermissionManagement.Domain</PackageId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Polly" Version="8.5.0" />
  </ItemGroup>
  <ItemGroup>
    
    <ProjectReference Include="..\..\..\..\framework\SufiChain.SufiAbp.Authorization\SufiChain.SufiAbp.Authorization.csproj" />
    
    <ProjectReference Include="..\..\..\..\framework\SufiChain.SufiAbp.Caching\SufiChain.SufiAbp.Caching.csproj" />
    
    <ProjectReference Include="..\..\..\..\framework\SufiChain.SufiAbp.Ddd.Domain\SufiChain.SufiAbp.Ddd.Domain.csproj" />
    
    <ProjectReference Include="..\..\..\..\framework\SufiChain.SufiAbp.DistributedLocking.Abstractions\SufiChain.SufiAbp.DistributedLocking.Abstractions.csproj" />
    
    <ProjectReference Include="..\SufiChain.SufiAbp.PermissionManagement.Domain.Shared\SufiChain.SufiAbp.PermissionManagement.Domain.Shared.csproj" />
  </ItemGroup>
</Project>
