<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>SufiChain.SufiAbp.PermissionManagement</RootNamespace>
    <PackageId>SufiChain.SufiAbp.PermissionManagement.Domain</PackageId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Polly" Version="8.5.0" />
  </ItemGroup>
  <ItemGroup>
    
    <ProjectReference Include="..\..\..\..\framework\SufiChain.SufiAbp.Authorization\SufiChain.SufiAbp.Authorization.csproj" />
    <PackageReference Include="Volo.Abp.Caching" Version="$(AbpVersion)" />
    <PackageReference Include="Volo.Abp.Ddd.Domain" Version="$(AbpVersion)" />
    <PackageReference Include="Volo.Abp.DistributedLocking.Abstractions" Version="$(AbpVersion)" />
    <ProjectReference Include="..\SufiChain.SufiAbp.PermissionManagement.Domain.Shared\SufiChain.SufiAbp.PermissionManagement.Domain.Shared.csproj" />
  </ItemGroup>
</Project>
