<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>SufiChain.SufiAbp.BackgroundJobs</RootNamespace>
    <PackageId>SufiChain.SufiAbp.BackgroundJobs.Domain</PackageId>
  </PropertyGroup>
  <ItemGroup>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Volo.Abp.Ddd.Domain" Version="$(AbpVersion)" />
    <PackageReference Include="Volo.Abp.BackgroundJobs" Version="$(AbpVersion)" />
    <PackageReference Include="Volo.Abp.Mapperly" Version="$(AbpVersion)" />
    <ProjectReference Include="..\SufiChain.SufiAbp.BackgroundJobs.Domain.Shared\SufiChain.SufiAbp.BackgroundJobs.Domain.Shared.csproj" />
  </ItemGroup>
</Project>
