<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>SufiChain.SufiAbp.FileManager</RootNamespace>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>SufiChain.SufiAbp.FileManager.HttpApi</PackageId>
    <Description>File manager module HTTP API controllers for Sufi Platform.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../../../framework/SufiChain.SufiAbp.AspNetCore.Mvc/SufiChain.SufiAbp.AspNetCore.Mvc.csproj" />
    <ProjectReference Include="../../../../framework/SufiChain.SufiAbp.UI.Domain.Shared/SufiChain.SufiAbp.UI.Domain.Shared.csproj" />
    <ProjectReference Include="..\SufiChain.SufiAbp.FileManager.Application.Contracts\SufiChain.SufiAbp.FileManager.Application.Contracts.csproj" />
  </ItemGroup>

</Project>
