<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>SufiChain.SufiPlatform.Settings</RootNamespace>
    <PackageId>SufiChain.SufiPlatform.Settings.EntityFrameworkCore</PackageId>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SufiChain.SufiPlatform.Settings.Domain\SufiChain.SufiPlatform.Settings.Domain.csproj" />
    <PackageReference Include="Volo.Abp.EntityFrameworkCore" Version="$(AbpVersion)" />
  </ItemGroup>
</Project>
