<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.1;net10.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <RootNamespace>SufiChain.SufiPlatform.Editions</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../../framework/SufiChain.SufiPlatform.Ddd.Application.Contracts/SufiChain.SufiPlatform.Ddd.Application.Contracts.csproj" />
    <ProjectReference Include="../../../../framework/SufiChain.SufiPlatform.Authorization/SufiChain.SufiPlatform.Authorization.csproj" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../SufiChain.SufiPlatform.Editions.Domain.Shared/SufiChain.SufiPlatform.Editions.Domain.Shared.csproj" />
  </ItemGroup>
</Project>
