<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>SufiChain.SufiAbp.Calendar</RootNamespace>
  </PropertyGroup>
  <PropertyGroup>
    <PackageId>SufiChain.SufiAbp.Calendar.MongoDB</PackageId>
    <Description>Calendar module MongoDB implementation for Sufi Platform.</Description>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../../framework/SufiChain.SufiAbp.MongoDB/SufiChain.SufiAbp.MongoDB.csproj" />
    <ProjectReference Include="..\SufiChain.SufiAbp.Calendar.Domain\SufiChain.SufiAbp.Calendar.Domain.csproj" />
  </ItemGroup>
</Project>
