<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>SufiChain.SufiAbp.AI</RootNamespace>
    <PackageId>SufiChain.SufiAbp.AI.HttpApi</PackageId>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../../../framework/SufiChain.SufiAbp.AI/SufiChain.SufiAbp.AI.csproj" />
    <ProjectReference Include="../../../../framework/SufiChain.SufiAbp.AspNetCore.Mvc/SufiChain.SufiAbp.AspNetCore.Mvc.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SufiChain.SufiAbp.AI.Application.Contracts\SufiChain.SufiAbp.AI.Application.Contracts.csproj" />
    <ProjectReference Include="..\SufiChain.SufiAbp.AI.Application\SufiChain.SufiAbp.AI.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.SemanticKernel" Version="1.76.0" />
  </ItemGroup>
</Project>
