<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>SufiChain.SufiAbp.AIManagement</RootNamespace>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\framework\SufiChain.SufiAbp.Ddd.Application\SufiChain.SufiAbp.Ddd.Application.csproj" />
    <ProjectReference Include="..\..\..\..\framework\SufiChain.SufiAbp.Mapperly\SufiChain.SufiAbp.Mapperly.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SufiChain.SufiAbp.AIManagement.Application.Contracts\SufiChain.SufiAbp.AIManagement.Application.Contracts.csproj" />
    <ProjectReference Include="..\SufiChain.SufiAbp.AIManagement.Domain\SufiChain.SufiAbp.AIManagement.Domain.csproj" />
  </ItemGroup>

</Project>
