<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>SufiChain.SufiPlatform.Features</RootNamespace>
    <PackageId>SufiChain.SufiPlatform.Features.Domain</PackageId>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Volo.Abp.Localization" Version="$(AbpVersion)" />
    <ProjectReference Include="../../../../framework/SufiChain.SufiPlatform.UI.Domain.Shared/SufiChain.SufiPlatform.UI.Domain.Shared.csproj" />
    <PackageReference Include="Volo.Abp.Ddd.Domain" Version="$(AbpVersion)" />
    <ProjectReference Include="..\..\..\..\framework\SufiChain.SufiPlatform.Features\SufiChain.SufiPlatform.Features.csproj" />
    <PackageReference Include="Volo.Abp.Caching" Version="$(AbpVersion)" />
    <ProjectReference Include="..\..\..\..\framework\SufiChain.SufiPlatform.Data\SufiChain.SufiPlatform.Data.csproj" />
    <ProjectReference Include="..\SufiChain.SufiPlatform.Features.Domain.Shared\SufiChain.SufiPlatform.Features.Domain.Shared.csproj" />
    <ProjectReference Include="..\..\..\tenants\src\SufiChain.SufiPlatform.Tenants.Application.Contracts\SufiChain.SufiPlatform.Tenants.Application.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Polly" Version="8.6.3" />
  </ItemGroup>

</Project>
