<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>MyCompanyName.MyProjectName.DbMigrator</RootNamespace>
    <LangVersion>latest</LangVersion>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Serilog.Extensions.Logging" Version="$(SerilogExtensionsLoggingVersion)" />
    <PackageReference Include="Serilog.Sinks.Async" Version="$(SerilogSinksAsyncVersion)" />
    <PackageReference Include="Serilog.Sinks.File" Version="$(SerilogSinksFileVersion)" />
    <PackageReference Include="Serilog.Sinks.Console" Version="$(SerilogSinksConsoleVersion)" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="$(MicrosoftExtensionsHostingVersion)" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SufiChain.SufiPlatform.Core" Version="$(SufiVersion)" />
    <PackageReference Include="Volo.Abp.Autofac" Version="$(AbpVersion)" />
    <ProjectReference Include="..\MyCompanyName.MyProjectName.Application\MyCompanyName.MyProjectName.Application.csproj" />
    <ProjectReference Include="..\MyCompanyName.MyProjectName.Application.Contracts\MyCompanyName.MyProjectName.Application.Contracts.csproj" />
    <!-- <TEMPLATE-REMOVE IF-NOT="db:efcore"> -->
    <ProjectReference Include="..\MyCompanyName.MyProjectName.EntityFrameworkCore\MyCompanyName.MyProjectName.EntityFrameworkCore.csproj" />
    <!-- </TEMPLATE-REMOVE> -->
    <!-- <TEMPLATE-REMOVE IF-NOT="db:mongodb"> -->
    <ProjectReference Include="..\MyCompanyName.MyProjectName.MongoDB\MyCompanyName.MyProjectName.MongoDB.csproj" />
    <!-- </TEMPLATE-REMOVE> -->
  </ItemGroup>

  
  
  <!-- <TEMPLATE-REMOVE> -->
  <ItemGroup>
    <ProjectReference Include="..\..\..\..\..\modules\file-manager\src\SufiChain.SufiPlatform.FileManager.Application\SufiChain.SufiPlatform.FileManager.Application.csproj" />
    <!-- <TEMPLATE-REMOVE IF-NOT="db:efcore"> -->
    <ProjectReference Include="..\..\..\..\..\modules\file-manager\src\SufiChain.SufiPlatform.FileManager.EntityFrameworkCore\SufiChain.SufiPlatform.FileManager.EntityFrameworkCore.csproj" />
    <!-- </TEMPLATE-REMOVE> -->
    <!-- <TEMPLATE-REMOVE IF-NOT="db:mongodb"> -->
    <ProjectReference Include="..\..\..\..\..\modules\file-manager\src\SufiChain.SufiPlatform.FileManager.MongoDB\SufiChain.SufiPlatform.FileManager.MongoDB.csproj" />
    <!-- </TEMPLATE-REMOVE> -->
    <ProjectReference Include="..\..\..\..\..\modules\audit-logging\src\SufiChain.SufiPlatform.AuditLogging.Application\SufiChain.SufiPlatform.AuditLogging.Application.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\jobs\src\SufiChain.SufiPlatform.BackgroundJobs.Application\SufiChain.SufiPlatform.BackgroundJobs.Application.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\identity\src\SufiChain.SufiPlatform.Identity.Application\SufiChain.SufiPlatform.Identity.Application.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\tenants\src\SufiChain.SufiPlatform.Tenants.Application\SufiChain.SufiPlatform.Tenants.Application.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\localization\src\SufiChain.SufiPlatform.Localization.Application\SufiChain.SufiPlatform.Localization.Application.csproj" />
    <!-- <TEMPLATE-REMOVE IF-NOT="db:efcore"> -->
    <ProjectReference Include="..\..\..\..\..\modules\localization\src\SufiChain.SufiPlatform.Localization.EntityFrameworkCore\SufiChain.SufiPlatform.Localization.EntityFrameworkCore.csproj" />
    <!-- </TEMPLATE-REMOVE> -->
    <!-- <TEMPLATE-REMOVE IF-NOT="db:mongodb"> -->
    <ProjectReference Include="..\..\..\..\..\modules\localization\src\SufiChain.SufiPlatform.Localization.MongoDB\SufiChain.SufiPlatform.Localization.MongoDB.csproj" />
    <!-- </TEMPLATE-REMOVE> -->
    <ProjectReference Include="..\..\..\..\..\modules\short-links\src\SufiChain.SufiPlatform.ShortLinks.Application\SufiChain.SufiPlatform.ShortLinks.Application.csproj" />
    <ProjectReference Include="..\..\..\..\..\modules\ai\src\SufiChain.SufiPlatform.SufiAI.Application\SufiChain.SufiPlatform.SufiAI.Application.csproj" />
    <!-- <TEMPLATE-REMOVE IF-NOT="db:efcore"> -->
    <ProjectReference Include="..\..\..\..\..\modules\short-links\src\SufiChain.SufiPlatform.ShortLinks.EntityFrameworkCore\SufiChain.SufiPlatform.ShortLinks.EntityFrameworkCore.csproj" />
    <!-- </TEMPLATE-REMOVE> -->
    <!-- <TEMPLATE-REMOVE IF-NOT="db:mongodb"> -->
    <ProjectReference Include="..\..\..\..\..\modules\short-links\src\SufiChain.SufiPlatform.ShortLinks.MongoDB\SufiChain.SufiPlatform.ShortLinks.MongoDB.csproj" />
    <!-- </TEMPLATE-REMOVE> -->
  </ItemGroup>
  <!-- </TEMPLATE-REMOVE> -->

  <!-- <TEMPLATE-ONLY>
  <ItemGroup>
    <PackageReference Include="SufiChain.SufiPlatform.Calendar.Application" Version="$(SufiVersion)" />
    <!-- <TEMPLATE-REMOVE IF-NOT="db:efcore"> -->
    <PackageReference Include="SufiChain.SufiPlatform.Calendar.EntityFrameworkCore" Version="$(SufiVersion)" />
    <!-- </TEMPLATE-REMOVE> -->
    <PackageReference Include="SufiChain.SufiPlatform.FileManager.Application" Version="$(SufiVersion)" />
    <!-- <TEMPLATE-REMOVE IF-NOT="db:efcore"> -->
    <PackageReference Include="SufiChain.SufiPlatform.FileManager.EntityFrameworkCore" Version="$(SufiVersion)" />
    <!-- </TEMPLATE-REMOVE> -->
    <!-- <TEMPLATE-REMOVE IF-NOT="db:mongodb"> -->
    <PackageReference Include="SufiChain.SufiPlatform.FileManager.MongoDB" Version="$(SufiVersion)" />
    <!-- </TEMPLATE-REMOVE> -->
    <PackageReference Include="SufiChain.SufiPlatform.AuditLogging.Application" Version="$(SufiVersion)" />
    <PackageReference Include="SufiChain.SufiPlatform.BackgroundJobs.Application" Version="$(SufiVersion)" />
    <PackageReference Include="SufiChain.SufiPlatform.Identity.Application" Version="$(SufiVersion)" />
    <PackageReference Include="SufiChain.SufiPlatform.Tenants.Application" Version="$(SufiVersion)" />
    <PackageReference Include="SufiChain.SufiPlatform.Localization.Application" Version="$(SufiVersion)" />
    <!-- <TEMPLATE-REMOVE IF-NOT="db:efcore"> -->
    <PackageReference Include="SufiChain.SufiPlatform.Localization.EntityFrameworkCore" Version="$(SufiVersion)" />
    <!-- </TEMPLATE-REMOVE> -->
    <!-- <TEMPLATE-REMOVE IF-NOT="db:mongodb"> -->
    <PackageReference Include="SufiChain.SufiPlatform.Localization.MongoDB" Version="$(SufiVersion)" />
    <!-- </TEMPLATE-REMOVE> -->
    <PackageReference Include="SufiChain.SufiPlatform.ShortLinks.Application" Version="$(SufiVersion)" />
    <PackageReference Include="SufiChain.SufiPlatform.SufiAI.Application" Version="$(SufiVersion)" />
    <!-- <TEMPLATE-REMOVE IF-NOT="db:efcore"> -->
    <PackageReference Include="SufiChain.SufiPlatform.ShortLinks.EntityFrameworkCore" Version="$(SufiVersion)" />
    <PackageReference Include="SufiChain.SufiPlatform.SufiAI.EntityFrameworkCore" Version="$(SufiVersion)" />
    <!-- </TEMPLATE-REMOVE> -->
    <!-- <TEMPLATE-REMOVE IF-NOT="db:mongodb"> -->
    <PackageReference Include="SufiChain.SufiPlatform.ShortLinks.MongoDB" Version="$(SufiVersion)" />
    <!-- </TEMPLATE-REMOVE> -->
  </ItemGroup>
  </TEMPLATE-ONLY> -->

  <ItemGroup>
    <Compile Remove="Logs\**" />
    <Content Remove="Logs\**" />
    <EmbeddedResource Remove="Logs\**" />
    <None Remove="Logs\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="appsettings.json" />
    <Content Include="appsettings.json">
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <None Remove="appsettings.secrets.json" />
    <Content Include="appsettings.secrets.json">
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
