<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>SufiChain.SufiPlatform.FileManager</RootNamespace>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>SufiChain.SufiPlatform.FileManager.HttpApi</PackageId>
    <Description>File manager module HTTP API controllers for Sufi Platform.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../../../framework/SufiChain.SufiPlatform.AspNetCore.Mvc/SufiChain.SufiPlatform.AspNetCore.Mvc.csproj" />
    <ProjectReference Include="../../../../framework/SufiChain.SufiPlatform.UI.Domain.Shared/SufiChain.SufiPlatform.UI.Domain.Shared.csproj" />
    <ProjectReference Include="..\..\..\..\framework\SufiChain.SufiPlatform.FileManager.Abstractions\SufiChain.SufiPlatform.FileManager.Abstractions.csproj" />
    <ProjectReference Include="..\SufiChain.SufiPlatform.FileManager.Application.Contracts\SufiChain.SufiPlatform.FileManager.Application.Contracts.csproj" />
  </ItemGroup>

</Project>
