<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>SufiChain.SufiAbp.Autofac</RootNamespace>
    <PackageId>SufiChain.SufiAbp.Autofac</PackageId>
    <Description>Autofac integration for SufiAbp applications.</Description>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Volo.Abp.Autofac" Version="$(AbpVersion)"/>
  </ItemGroup>
</Project>
