<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.1;net10.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>SufiChain.SufiPlatform.Identity</RootNamespace>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>SufiChain.SufiPlatform.Identity.Application.Contracts</PackageId>
    <Description>Identity module application contracts for Sufi Platform - DTOs and service interfaces.</Description>
  </PropertyGroup>

  <ItemGroup>
    <!-- ABP Dependencies -->
    <ProjectReference Include="../../../../framework/SufiChain.SufiPlatform.Ddd.Application.Contracts/SufiChain.SufiPlatform.Ddd.Application.Contracts.csproj" />
    <ProjectReference Include="../../../../framework/SufiChain.SufiPlatform.Authorization/SufiChain.SufiPlatform.Authorization.csproj" />
    <!-- Sufi Domain.Shared for localization -->
    <ProjectReference Include="..\SufiChain.SufiPlatform.Identity.Domain.Shared\SufiChain.SufiPlatform.Identity.Domain.Shared.csproj" />
    <ProjectReference Include="../../../users/src/SufiChain.SufiPlatform.Users.Abstractions/SufiChain.SufiPlatform.Users.Abstractions.csproj" />
  </ItemGroup>

</Project>
