<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>SufiChain.SufiAbp.FileManager</RootNamespace>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>SufiChain.SufiAbp.FileManager.Application</PackageId>
    <Description>File manager module application services for Sufi Platform - file operations and image processing.</Description>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="../../../../framework/SufiChain.SufiAbp.Core/SufiChain.SufiAbp.Core.csproj" />
    <PackageReference Include="Volo.Abp.Mapperly" Version="$(AbpVersion)" />
    <PackageReference Include="Volo.Abp.Caching" Version="$(AbpVersion)" />
    <PackageReference Include="Volo.Abp.BackgroundWorkers" Version="$(AbpVersion)" />
    <ProjectReference Include="../../../tenant-management/src/SufiChain.SufiAbp.TenantManagement.Domain/SufiChain.SufiAbp.TenantManagement.Domain.csproj" />
    <ProjectReference Include="../../../../framework/SufiChain.SufiAbp.Ddd.Application/SufiChain.SufiAbp.Ddd.Application.csproj" />
    <PackageReference Include="Volo.Abp.BlobStoring" Version="$(AbpVersion)" />
    <PackageReference Include="Volo.Abp.BlobStoring.FileSystem" Version="$(AbpVersion)" />
    <PackageReference Include="Volo.Abp.BlobStoring.Minio" Version="$(AbpVersion)" />
    <ProjectReference Include="..\..\..\..\framework\SufiChain.SufiAbp.BlobStoring.S3Provider\SufiChain.SufiAbp.BlobStoring.S3Provider.csproj" />
    <PackageReference Include="Volo.Abp.Security" Version="$(AbpVersion)" />
    <ProjectReference Include="../../../setting-management/src/SufiChain.SufiAbp.SettingManagement.Domain/SufiChain.SufiAbp.SettingManagement.Domain.csproj" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="$(MicrosoftDataSqlClientVersion)" />
    <PackageReference Include="Volo.Abp.Threading" Version="$(AbpVersion)" />
    <ProjectReference Include="../../../../framework/SufiChain.SufiAbp.Data/SufiChain.SufiAbp.Data.csproj" />
    <PackageReference Include="Volo.Abp.Guids" Version="$(AbpVersion)" />
    <PackageReference Include="SixLabors.ImageSharp" Version="$(SixLaborsImageSharpVersion)" />
    <PackageReference Include="FFMpegCore" Version="$(FFMpegCoreVersion)" />
    <ProjectReference Include="..\..\..\localization-management\src\SufiChain.SufiAbp.LocalizationManagement.Application.Contracts\SufiChain.SufiAbp.LocalizationManagement.Application.Contracts.csproj" />
    <ProjectReference Include="..\SufiChain.SufiAbp.FileManager.Application.Contracts\SufiChain.SufiAbp.FileManager.Application.Contracts.csproj" />
    <ProjectReference Include="..\SufiChain.SufiAbp.FileManager.Domain.Shared\SufiChain.SufiAbp.FileManager.Domain.Shared.csproj" />
    <ProjectReference Include="..\SufiChain.SufiAbp.FileManager.Domain\SufiChain.SufiAbp.FileManager.Domain.csproj" />
  </ItemGroup>

</Project>
