<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.1;net10.0</TargetFrameworks>
    <RootNamespace>SufiChain.SufiAbp.AIManagement</RootNamespace>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\framework\SufiChain.SufiAbp.Http.Client\SufiChain.SufiAbp.Http.Client.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SufiChain.SufiAbp.AIManagement.Application.Contracts\SufiChain.SufiAbp.AIManagement.Application.Contracts.csproj" />
  </ItemGroup>

</Project>
