<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <PackageId>SufiChain.SufiAbp.TenantManagement.EntityFrameworkCore</PackageId>
    <RootNamespace>SufiChain.SufiAbp.TenantManagement</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SufiChain.SufiAbp.TenantManagement.Domain\SufiChain.SufiAbp.TenantManagement.Domain.csproj" />
    <PackageReference Include="Volo.Abp.EntityFrameworkCore" Version="$(AbpVersion)" />
  </ItemGroup>
</Project>
