<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>SufiChain.SufiAbp.SettingManagement</RootNamespace>
    <PackageId>SufiChain.SufiAbp.SettingManagement.MongoDB</PackageId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Volo.Abp.MongoDB" Version="$(AbpVersion)" />
    <ProjectReference Include="..\SufiChain.SufiAbp.SettingManagement.Domain\SufiChain.SufiAbp.SettingManagement.Domain.csproj" />
  </ItemGroup>
</Project>
