<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>SufiChain.SufiPlatform.Tenants</RootNamespace>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../modules/tenants/src/SufiChain.SufiPlatform.Tenants.Domain.Shared/SufiChain.SufiPlatform.Tenants.Domain.Shared.csproj" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="$(MicrosoftNetTestSdkVersion)" />
    <PackageReference Include="xunit" Version="$(XunitVersion)" />
    <PackageReference Include="xunit.runner.visualstudio" Version="$(XunitRunnerVisualStudioVersion)" PrivateAssets="All" />
    <PackageReference Include="Shouldly" Version="$(ShouldlyVersion)" />
  </ItemGroup>
</Project>
