<Project Sdk="Microsoft.NET.Sdk">


  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;netstandard2.1;net10.0</TargetFrameworks>
    <AssemblyName>SufiChain.SufiAbp.EventBus</AssemblyName>
    <PackageId>SufiChain.SufiAbp.EventBus</PackageId>
    <RootNamespace>SufiChain.SufiAbp.EventBus</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.EventBus" Version="10.3.0" />
  </ItemGroup>

</Project>
