<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>SufiChain.SufiPlatform.OpenIddict</RootNamespace>
    <PackageId>SufiChain.SufiPlatform.OpenIddict.EntityFrameworkCore</PackageId>
    <Description>Entity Framework Core integration for Sufi OpenIddict.</Description>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Volo.Abp.EntityFrameworkCore" Version="$(AbpVersion)" />
    <ProjectReference Include="..\SufiChain.SufiPlatform.OpenIddict.Domain\SufiChain.SufiPlatform.OpenIddict.Domain.csproj" />
  </ItemGroup>
</Project>
