<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>SufiChain.SufiPlatform.FileManager</RootNamespace>
    <OutputType>Library</OutputType>
    <GenerateRuntimeConfigurationFiles>false</GenerateRuntimeConfigurationFiles>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>SufiChain.SufiPlatform.FileManager.EntityFrameworkCore</PackageId>
    <Description>File manager module Entity Framework Core implementation for Sufi Platform.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.EntityFrameworkCore" Version="$(AbpVersion)" />
    <ProjectReference Include="../../../blob-database/src/SufiChain.SufiPlatform.BlobDatabase.EntityFrameworkCore/SufiChain.SufiPlatform.BlobDatabase.EntityFrameworkCore.csproj" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="$(MicrosoftEntityFrameworkCoreVersion)" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="$(MicrosoftEntityFrameworkCoreVersion)">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <ProjectReference Include="..\SufiChain.SufiPlatform.FileManager.Domain\SufiChain.SufiPlatform.FileManager.Domain.csproj" />
  </ItemGroup>

</Project>
