<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>SufiChain.Chat.Blazor.Server</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SufiChain.Chat.Blazor.Public\SufiChain.Chat.Blazor.Public.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SufiChain.Chat.Blazor\SufiChain.Chat.Blazor.csproj" />
  </ItemGroup>
</Project>
