<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>SufiChain.SufiPlatform.SufiCom.Chat</RootNamespace>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SufiChain.SufiPlatform.SufiCom.Chat.TestBase\SufiChain.SufiPlatform.SufiCom.Chat.TestBase.csproj" />
    <ProjectReference Include="..\..\..\..\pro-modules\suficom\chat\src\SufiChain.SufiPlatform.SufiCom.Chat.Application\SufiChain.SufiPlatform.SufiCom.Chat.Application.csproj" />
    <ProjectReference Include="..\..\..\..\pro-modules\suficom\channels\src\SufiChain.SufiPlatform.SufiCom.Channels\SufiChain.SufiPlatform.SufiCom.Channels.csproj" />
    <ProjectReference Include="..\..\..\..\pro-modules\suficom\channels\src\SufiChain.SufiPlatform.SufiCom.Channels.Telegram\SufiChain.SufiPlatform.SufiCom.Channels.Telegram.csproj" />
    <ProjectReference Include="..\..\..\..\pro-modules\suficom\src\SufiChain.SufiPlatform.SufiCom.Application\SufiChain.SufiPlatform.SufiCom.Application.csproj" />
    <ProjectReference Include="..\..\..\..\pro-modules\suficom\chat\src\SufiChain.SufiPlatform.SufiCom.Chat.EntityFrameworkCore\SufiChain.SufiPlatform.SufiCom.Chat.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\..\..\modules\settings\src\SufiChain.SufiPlatform.Settings.EntityFrameworkCore\SufiChain.SufiPlatform.Settings.EntityFrameworkCore.csproj" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="NSubstitute" Version="5.3.0" />
    <PackageReference Include="Shouldly" Version="4.3.0" />
    <PackageReference Include="Volo.Abp.EntityFrameworkCore.Sqlite" Version="$(AbpVersion)" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>
</Project>
