<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>SufiChain.SufiPlatform.Calendar</RootNamespace>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="$(MicrosoftNetTestSdkVersion)" />
    <PackageReference Include="xunit.runner.visualstudio" Version="$(XunitRunnerVisualStudioVersion)" PrivateAssets="all" />
    <PackageReference Include="Mongo2Go" Version="$(Mongo2GoVersion)" />
    <ProjectReference Include="..\SufiChain.SufiPlatform.Calendar.TestBase\SufiChain.SufiPlatform.Calendar.TestBase.csproj" />
    <ProjectReference Include="..\..\..\modules\calendar\src\SufiChain.SufiPlatform.Calendar.Application\SufiChain.SufiPlatform.Calendar.Application.csproj" />
    <ProjectReference Include="..\..\..\modules\calendar\src\SufiChain.SufiPlatform.Calendar.MongoDB\SufiChain.SufiPlatform.Calendar.MongoDB.csproj" />
  </ItemGroup>
</Project>
