<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
        <TargetFrameworks>netstandard2.1;net10.0</TargetFrameworks>
    <RootNamespace>SufiChain.SufiPlatform.SufiAI</RootNamespace>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\framework\SufiChain.SufiPlatform.Ddd.Application.Contracts\SufiChain.SufiPlatform.Ddd.Application.Contracts.csproj" />
    <ProjectReference Include="..\..\..\..\framework\SufiChain.SufiPlatform.Authorization\SufiChain.SufiPlatform.Authorization.csproj" />
    <ProjectReference Include="..\..\..\file-manager\src\SufiChain.SufiPlatform.FileManager.Application.Contracts\SufiChain.SufiPlatform.FileManager.Application.Contracts.csproj" />
    <ProjectReference Include="..\..\..\file-manager\src\SufiChain.SufiPlatform.FileManager.Domain.Shared\SufiChain.SufiPlatform.FileManager.Domain.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SufiChain.SufiPlatform.SufiAI.Domain.Shared\SufiChain.SufiPlatform.SufiAI.Domain.Shared.csproj" />
  </ItemGroup>

</Project>
