<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>SufiChain.SufiPlatform.SufiAI.Blazor.WebAssembly</RootNamespace>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SufiChain.SufiPlatform.SufiAI.Blazor\SufiChain.SufiPlatform.SufiAI.Blazor.csproj" />
    <ProjectReference Include="..\SufiChain.SufiPlatform.SufiAI.HttpApi.Client\SufiChain.SufiPlatform.SufiAI.HttpApi.Client.csproj" />
  </ItemGroup>

</Project>
