<Project Sdk="Microsoft.NET.Sdk">


    <PropertyGroup>
		<TargetFrameworks>netstandard2.1;net10.0</TargetFrameworks>
        <Nullable>enable</Nullable>
        <RootNamespace>SufiChain.SufiAbp.ShortLinkGenerator</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
    <PackageReference Include="Volo.Abp.Http.Client" Version="$(AbpVersion)" />
  </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\SufiChain.SufiAbp.ShortLinkGenerator.Application.Contracts\SufiChain.SufiAbp.ShortLinkGenerator.Application.Contracts.csproj" />
    </ItemGroup>

</Project>

