<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>SufiChain.SufiAbp.LocalizationManagement</RootNamespace>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>SufiChain.SufiAbp.LocalizationManagement.MongoDB</PackageId>
    <Description>Localization management module MongoDB implementation for Sufi Platform.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.MongoDB" Version="$(AbpVersion)" />
    <ProjectReference Include="..\SufiChain.SufiAbp.LocalizationManagement.Domain\SufiChain.SufiAbp.LocalizationManagement.Domain.csproj" />
  </ItemGroup>

</Project>
