<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFrameworks>netstandard2.1;net10.0</TargetFrameworks>
	  <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>SufiChain.SufiPlatform.AspNetCore.Authentication</RootNamespace>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>SufiChain.SufiPlatform.AspNetCore.Authentication.Abstractions</PackageId>
    <Description>Shared authentication abstractions for Sufi Platform Blazor applications.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Options" Version="$(AspNetCoreVersion)" />
  </ItemGroup>

</Project>
