<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>SufiChain.SufiAbp.UI.Blazor.Server</RootNamespace>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>SufiChain.SufiAbp.UI.Blazor.Server</PackageId>
    <Description>Blazor Server specific implementations for Sufi Platform UI.</Description>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.MultiTenancy" Version="$(AbpVersion)" />
    <ProjectReference Include="..\SufiChain.SufiAbp.UI.Blazor\SufiChain.SufiAbp.UI.Blazor.csproj" />
    <ProjectReference Include="..\SufiChain.SufiAbp.UI.Services\SufiChain.SufiAbp.UI.Services.csproj" />
  </ItemGroup>

</Project>
