<Project Sdk="Microsoft.NET.Sdk">


    <PropertyGroup>
		<TargetFrameworks>netstandard2.1;net10.0</TargetFrameworks>
        <Nullable>enable</Nullable>
        <RootNamespace>SufiChain.SufiPlatform.ShortLinks</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
    <PackageReference Include="Volo.Abp.Http.Client" Version="$(AbpVersion)" />
  </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\SufiChain.SufiPlatform.ShortLinks.Application.Contracts\SufiChain.SufiPlatform.ShortLinks.Application.Contracts.csproj" />
    </ItemGroup>

</Project>

