<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>SufiChain.SufiAbp.EntityFrameworkCore.MySQL</RootNamespace>
    <PackageId>SufiChain.SufiAbp.EntityFrameworkCore.MySQL</PackageId>
    <Description>MySQL provider integration for SufiAbp Entity Framework Core.</Description>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Volo.Abp.EntityFrameworkCore.MySQL" Version="$(AbpVersion)"/>
  </ItemGroup>
</Project>
