<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>SufiChain.SufiPlatform.Editions</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Volo.Abp.Mapperly" Version="$(AbpVersion)" />
    <ProjectReference Include="../../../../framework/SufiChain.SufiPlatform.Ddd.Application/SufiChain.SufiPlatform.Ddd.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../SufiChain.SufiPlatform.Editions.Domain/SufiChain.SufiPlatform.Editions.Domain.csproj" />
    <ProjectReference Include="../SufiChain.SufiPlatform.Editions.Application.Contracts/SufiChain.SufiPlatform.Editions.Application.Contracts.csproj" />
  </ItemGroup>
</Project>
