<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
		<TargetFrameworks>net10.0</TargetFrameworks>
        <Nullable>enable</Nullable>
        <RootNamespace>SufiChain.SufiAbp.ShortLinkGenerator.MongoDB</RootNamespace>
        <PackageId>SufiChain.SufiAbp.ShortLinkGenerator.MongoDB</PackageId>
    </PropertyGroup>

    <ItemGroup>
    <PackageReference Include="Volo.Abp.MongoDB" Version="$(AbpVersion)" />
  </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\SufiChain.SufiAbp.ShortLinkGenerator.Domain\SufiChain.SufiAbp.ShortLinkGenerator.Domain.csproj" />
    </ItemGroup>

</Project>
