<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>SufiChain.SufiAbp.FileManager</RootNamespace>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>SufiChain.SufiAbp.FileManager.MongoDB</PackageId>
    <Description>File manager module MongoDB implementation for Sufi Platform.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.MongoDB" Version="$(AbpVersion)" />
    <ProjectReference Include="../../../blob-storing-database/src/SufiChain.SufiAbp.BlobStoring.Database.MongoDB/SufiChain.SufiAbp.BlobStoring.Database.MongoDB.csproj" />
    <ProjectReference Include="..\SufiChain.SufiAbp.FileManager.Domain\SufiChain.SufiAbp.FileManager.Domain.csproj" />
  </ItemGroup>

</Project>
