<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>SufiChain.SufiAbp.AI</RootNamespace>
    <PackageId>SufiChain.SufiAbp.AI.MongoDB</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.MongoDB" Version="$(AbpVersion)" />
    <ProjectReference Include="..\SufiChain.SufiAbp.AI.Domain\SufiChain.SufiAbp.AI.Domain.csproj" />
  </ItemGroup>

</Project>
